// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"time"

	models "github.com/JasonKhew96/stickers_bot/models"
)

type Factory struct {
	baseKeywordMods        KeywordModSlice
	baseStickerMods        StickerModSlice
	baseStickerKeywordMods StickerKeywordModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewKeyword(mods ...KeywordMod) *KeywordTemplate {
	return f.NewKeywordWithContext(context.Background(), mods...)
}

func (f *Factory) NewKeywordWithContext(ctx context.Context, mods ...KeywordMod) *KeywordTemplate {
	o := &KeywordTemplate{f: f}

	if f != nil {
		f.baseKeywordMods.Apply(ctx, o)
	}

	KeywordModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingKeyword(m *models.Keyword) *KeywordTemplate {
	o := &KeywordTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.Keyword = func() string { return m.Keyword }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	ctx := context.Background()
	if len(m.R.StickerKeywords) > 0 {
		KeywordMods.AddExistingStickerKeywords(m.R.StickerKeywords...).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewSticker(mods ...StickerMod) *StickerTemplate {
	return f.NewStickerWithContext(context.Background(), mods...)
}

func (f *Factory) NewStickerWithContext(ctx context.Context, mods ...StickerMod) *StickerTemplate {
	o := &StickerTemplate{f: f}

	if f != nil {
		f.baseStickerMods.Apply(ctx, o)
	}

	StickerModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingSticker(m *models.Sticker) *StickerTemplate {
	o := &StickerTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.FileID = func() string { return m.FileID }
	o.StickerType = func() string { return m.StickerType }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	ctx := context.Background()
	if len(m.R.StickerKeywords) > 0 {
		StickerMods.AddExistingStickerKeywords(m.R.StickerKeywords...).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewStickerKeyword(mods ...StickerKeywordMod) *StickerKeywordTemplate {
	return f.NewStickerKeywordWithContext(context.Background(), mods...)
}

func (f *Factory) NewStickerKeywordWithContext(ctx context.Context, mods ...StickerKeywordMod) *StickerKeywordTemplate {
	o := &StickerKeywordTemplate{f: f}

	if f != nil {
		f.baseStickerKeywordMods.Apply(ctx, o)
	}

	StickerKeywordModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingStickerKeyword(m *models.StickerKeyword) *StickerKeywordTemplate {
	o := &StickerKeywordTemplate{f: f, alreadyPersisted: true}

	o.StickerID = func() int64 { return m.StickerID }
	o.KeywordID = func() int64 { return m.KeywordID }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	ctx := context.Background()
	if m.R.Keyword != nil {
		StickerKeywordMods.WithExistingKeyword(m.R.Keyword).Apply(ctx, o)
	}
	if m.R.Sticker != nil {
		StickerKeywordMods.WithExistingSticker(m.R.Sticker).Apply(ctx, o)
	}

	return o
}

func (f *Factory) ClearBaseKeywordMods() {
	f.baseKeywordMods = nil
}

func (f *Factory) AddBaseKeywordMod(mods ...KeywordMod) {
	f.baseKeywordMods = append(f.baseKeywordMods, mods...)
}

func (f *Factory) ClearBaseStickerMods() {
	f.baseStickerMods = nil
}

func (f *Factory) AddBaseStickerMod(mods ...StickerMod) {
	f.baseStickerMods = append(f.baseStickerMods, mods...)
}

func (f *Factory) ClearBaseStickerKeywordMods() {
	f.baseStickerKeywordMods = nil
}

func (f *Factory) AddBaseStickerKeywordMod(mods ...StickerKeywordMod) {
	f.baseStickerKeywordMods = append(f.baseStickerKeywordMods, mods...)
}
