// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	models "github.com/JasonKhew96/stickers_bot/models"
	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type KeywordMod interface {
	Apply(context.Context, *KeywordTemplate)
}

type KeywordModFunc func(context.Context, *KeywordTemplate)

func (f KeywordModFunc) Apply(ctx context.Context, n *KeywordTemplate) {
	f(ctx, n)
}

type KeywordModSlice []KeywordMod

func (mods KeywordModSlice) Apply(ctx context.Context, n *KeywordTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// KeywordTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type KeywordTemplate struct {
	ID        func() int64
	Keyword   func() string
	CreatedAt func() time.Time
	UpdatedAt func() time.Time

	r keywordR
	f *Factory

	alreadyPersisted bool
}

type keywordR struct {
	StickerKeywords []*keywordRStickerKeywordsR
}

type keywordRStickerKeywordsR struct {
	number int
	o      *StickerKeywordTemplate
}

// Apply mods to the KeywordTemplate
func (o *KeywordTemplate) Apply(ctx context.Context, mods ...KeywordMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Keyword
// according to the relationships in the template. Nothing is inserted into the db
func (t KeywordTemplate) setModelRels(o *models.Keyword) {
	if t.r.StickerKeywords != nil {
		rel := models.StickerKeywordSlice{}
		for _, r := range t.r.StickerKeywords {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.KeywordID = o.ID // h2
				rel.R.Keyword = o
			}
			rel = append(rel, related...)
		}
		o.R.StickerKeywords = rel
	}
}

// BuildSetter returns an *models.KeywordSetter
// this does nothing with the relationship templates
func (o KeywordTemplate) BuildSetter() *models.KeywordSetter {
	m := &models.KeywordSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Keyword != nil {
		val := o.Keyword()
		m.Keyword = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.KeywordSetter
// this does nothing with the relationship templates
func (o KeywordTemplate) BuildManySetter(number int) []*models.KeywordSetter {
	m := make([]*models.KeywordSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Keyword
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use KeywordTemplate.Create
func (o KeywordTemplate) Build() *models.Keyword {
	m := &models.Keyword{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Keyword != nil {
		m.Keyword = o.Keyword()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.KeywordSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use KeywordTemplate.CreateMany
func (o KeywordTemplate) BuildMany(number int) models.KeywordSlice {
	m := make(models.KeywordSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableKeyword(m *models.KeywordSetter) {
	if !(m.Keyword.IsValue()) {
		val := random_string(nil)
		m.Keyword = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Keyword
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *KeywordTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Keyword) error {
	var err error

	isStickerKeywordsDone, _ := keywordRelStickerKeywordsCtx.Value(ctx)
	if !isStickerKeywordsDone && o.r.StickerKeywords != nil {
		ctx = keywordRelStickerKeywordsCtx.WithValue(ctx, true)
		for _, r := range o.r.StickerKeywords {
			if r.o.alreadyPersisted {
				m.R.StickerKeywords = append(m.R.StickerKeywords, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachStickerKeywords(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a keyword and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *KeywordTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Keyword, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableKeyword(opt)

	m, err := models.Keywords.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a keyword and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *KeywordTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Keyword {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a keyword and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *KeywordTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Keyword {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple keywords and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o KeywordTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.KeywordSlice, error) {
	var err error
	m := make(models.KeywordSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple keywords and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o KeywordTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.KeywordSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple keywords and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o KeywordTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.KeywordSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Keyword has methods that act as mods for the KeywordTemplate
var KeywordMods keywordMods

type keywordMods struct{}

func (m keywordMods) RandomizeAllColumns(f *faker.Faker) KeywordMod {
	return KeywordModSlice{
		KeywordMods.RandomID(f),
		KeywordMods.RandomKeyword(f),
		KeywordMods.RandomCreatedAt(f),
		KeywordMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m keywordMods) ID(val int64) KeywordMod {
	return KeywordModFunc(func(_ context.Context, o *KeywordTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m keywordMods) IDFunc(f func() int64) KeywordMod {
	return KeywordModFunc(func(_ context.Context, o *KeywordTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m keywordMods) UnsetID() KeywordMod {
	return KeywordModFunc(func(_ context.Context, o *KeywordTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m keywordMods) RandomID(f *faker.Faker) KeywordMod {
	return KeywordModFunc(func(_ context.Context, o *KeywordTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m keywordMods) Keyword(val string) KeywordMod {
	return KeywordModFunc(func(_ context.Context, o *KeywordTemplate) {
		o.Keyword = func() string { return val }
	})
}

// Set the Column from the function
func (m keywordMods) KeywordFunc(f func() string) KeywordMod {
	return KeywordModFunc(func(_ context.Context, o *KeywordTemplate) {
		o.Keyword = f
	})
}

// Clear any values for the column
func (m keywordMods) UnsetKeyword() KeywordMod {
	return KeywordModFunc(func(_ context.Context, o *KeywordTemplate) {
		o.Keyword = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m keywordMods) RandomKeyword(f *faker.Faker) KeywordMod {
	return KeywordModFunc(func(_ context.Context, o *KeywordTemplate) {
		o.Keyword = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m keywordMods) CreatedAt(val time.Time) KeywordMod {
	return KeywordModFunc(func(_ context.Context, o *KeywordTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m keywordMods) CreatedAtFunc(f func() time.Time) KeywordMod {
	return KeywordModFunc(func(_ context.Context, o *KeywordTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m keywordMods) UnsetCreatedAt() KeywordMod {
	return KeywordModFunc(func(_ context.Context, o *KeywordTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m keywordMods) RandomCreatedAt(f *faker.Faker) KeywordMod {
	return KeywordModFunc(func(_ context.Context, o *KeywordTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m keywordMods) UpdatedAt(val time.Time) KeywordMod {
	return KeywordModFunc(func(_ context.Context, o *KeywordTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m keywordMods) UpdatedAtFunc(f func() time.Time) KeywordMod {
	return KeywordModFunc(func(_ context.Context, o *KeywordTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m keywordMods) UnsetUpdatedAt() KeywordMod {
	return KeywordModFunc(func(_ context.Context, o *KeywordTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m keywordMods) RandomUpdatedAt(f *faker.Faker) KeywordMod {
	return KeywordModFunc(func(_ context.Context, o *KeywordTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m keywordMods) WithParentsCascading() KeywordMod {
	return KeywordModFunc(func(ctx context.Context, o *KeywordTemplate) {
		if isDone, _ := keywordWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = keywordWithParentsCascadingCtx.WithValue(ctx, true)
	})
}

func (m keywordMods) WithStickerKeywords(number int, related *StickerKeywordTemplate) KeywordMod {
	return KeywordModFunc(func(ctx context.Context, o *KeywordTemplate) {
		o.r.StickerKeywords = []*keywordRStickerKeywordsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m keywordMods) WithNewStickerKeywords(number int, mods ...StickerKeywordMod) KeywordMod {
	return KeywordModFunc(func(ctx context.Context, o *KeywordTemplate) {
		related := o.f.NewStickerKeywordWithContext(ctx, mods...)
		m.WithStickerKeywords(number, related).Apply(ctx, o)
	})
}

func (m keywordMods) AddStickerKeywords(number int, related *StickerKeywordTemplate) KeywordMod {
	return KeywordModFunc(func(ctx context.Context, o *KeywordTemplate) {
		o.r.StickerKeywords = append(o.r.StickerKeywords, &keywordRStickerKeywordsR{
			number: number,
			o:      related,
		})
	})
}

func (m keywordMods) AddNewStickerKeywords(number int, mods ...StickerKeywordMod) KeywordMod {
	return KeywordModFunc(func(ctx context.Context, o *KeywordTemplate) {
		related := o.f.NewStickerKeywordWithContext(ctx, mods...)
		m.AddStickerKeywords(number, related).Apply(ctx, o)
	})
}

func (m keywordMods) AddExistingStickerKeywords(existingModels ...*models.StickerKeyword) KeywordMod {
	return KeywordModFunc(func(ctx context.Context, o *KeywordTemplate) {
		for _, em := range existingModels {
			o.r.StickerKeywords = append(o.r.StickerKeywords, &keywordRStickerKeywordsR{
				o: o.f.FromExistingStickerKeyword(em),
			})
		}
	})
}

func (m keywordMods) WithoutStickerKeywords() KeywordMod {
	return KeywordModFunc(func(ctx context.Context, o *KeywordTemplate) {
		o.r.StickerKeywords = nil
	})
}
