// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	models "github.com/JasonKhew96/stickers_bot/models"
	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type RecentStickerMod interface {
	Apply(context.Context, *RecentStickerTemplate)
}

type RecentStickerModFunc func(context.Context, *RecentStickerTemplate)

func (f RecentStickerModFunc) Apply(ctx context.Context, n *RecentStickerTemplate) {
	f(ctx, n)
}

type RecentStickerModSlice []RecentStickerMod

func (mods RecentStickerModSlice) Apply(ctx context.Context, n *RecentStickerTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// RecentStickerTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type RecentStickerTemplate struct {
	ID        func() int64
	Recents   func() null.Val[string]
	CreatedAt func() time.Time
	UpdatedAt func() time.Time

	f *Factory

	alreadyPersisted bool
}

// Apply mods to the RecentStickerTemplate
func (o *RecentStickerTemplate) Apply(ctx context.Context, mods ...RecentStickerMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.RecentSticker
// according to the relationships in the template. Nothing is inserted into the db
func (t RecentStickerTemplate) setModelRels(o *models.RecentSticker) {}

// BuildSetter returns an *models.RecentStickerSetter
// this does nothing with the relationship templates
func (o RecentStickerTemplate) BuildSetter() *models.RecentStickerSetter {
	m := &models.RecentStickerSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Recents != nil {
		val := o.Recents()
		m.Recents = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.RecentStickerSetter
// this does nothing with the relationship templates
func (o RecentStickerTemplate) BuildManySetter(number int) []*models.RecentStickerSetter {
	m := make([]*models.RecentStickerSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.RecentSticker
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use RecentStickerTemplate.Create
func (o RecentStickerTemplate) Build() *models.RecentSticker {
	m := &models.RecentSticker{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Recents != nil {
		m.Recents = o.Recents()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.RecentStickerSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use RecentStickerTemplate.CreateMany
func (o RecentStickerTemplate) BuildMany(number int) models.RecentStickerSlice {
	m := make(models.RecentStickerSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableRecentSticker(m *models.RecentStickerSetter) {
}

// insertOptRels creates and inserts any optional the relationships on *models.RecentSticker
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *RecentStickerTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.RecentSticker) error {
	var err error

	return err
}

// Create builds a recentSticker and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *RecentStickerTemplate) Create(ctx context.Context, exec bob.Executor) (*models.RecentSticker, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableRecentSticker(opt)

	m, err := models.RecentStickers.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a recentSticker and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *RecentStickerTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.RecentSticker {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a recentSticker and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *RecentStickerTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.RecentSticker {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple recentStickers and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o RecentStickerTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.RecentStickerSlice, error) {
	var err error
	m := make(models.RecentStickerSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple recentStickers and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o RecentStickerTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.RecentStickerSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple recentStickers and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o RecentStickerTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.RecentStickerSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// RecentSticker has methods that act as mods for the RecentStickerTemplate
var RecentStickerMods recentStickerMods

type recentStickerMods struct{}

func (m recentStickerMods) RandomizeAllColumns(f *faker.Faker) RecentStickerMod {
	return RecentStickerModSlice{
		RecentStickerMods.RandomID(f),
		RecentStickerMods.RandomRecents(f),
		RecentStickerMods.RandomCreatedAt(f),
		RecentStickerMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m recentStickerMods) ID(val int64) RecentStickerMod {
	return RecentStickerModFunc(func(_ context.Context, o *RecentStickerTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m recentStickerMods) IDFunc(f func() int64) RecentStickerMod {
	return RecentStickerModFunc(func(_ context.Context, o *RecentStickerTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m recentStickerMods) UnsetID() RecentStickerMod {
	return RecentStickerModFunc(func(_ context.Context, o *RecentStickerTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m recentStickerMods) RandomID(f *faker.Faker) RecentStickerMod {
	return RecentStickerModFunc(func(_ context.Context, o *RecentStickerTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m recentStickerMods) Recents(val null.Val[string]) RecentStickerMod {
	return RecentStickerModFunc(func(_ context.Context, o *RecentStickerTemplate) {
		o.Recents = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m recentStickerMods) RecentsFunc(f func() null.Val[string]) RecentStickerMod {
	return RecentStickerModFunc(func(_ context.Context, o *RecentStickerTemplate) {
		o.Recents = f
	})
}

// Clear any values for the column
func (m recentStickerMods) UnsetRecents() RecentStickerMod {
	return RecentStickerModFunc(func(_ context.Context, o *RecentStickerTemplate) {
		o.Recents = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m recentStickerMods) RandomRecents(f *faker.Faker) RecentStickerMod {
	return RecentStickerModFunc(func(_ context.Context, o *RecentStickerTemplate) {
		o.Recents = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m recentStickerMods) RandomRecentsNotNull(f *faker.Faker) RecentStickerMod {
	return RecentStickerModFunc(func(_ context.Context, o *RecentStickerTemplate) {
		o.Recents = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m recentStickerMods) CreatedAt(val time.Time) RecentStickerMod {
	return RecentStickerModFunc(func(_ context.Context, o *RecentStickerTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m recentStickerMods) CreatedAtFunc(f func() time.Time) RecentStickerMod {
	return RecentStickerModFunc(func(_ context.Context, o *RecentStickerTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m recentStickerMods) UnsetCreatedAt() RecentStickerMod {
	return RecentStickerModFunc(func(_ context.Context, o *RecentStickerTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m recentStickerMods) RandomCreatedAt(f *faker.Faker) RecentStickerMod {
	return RecentStickerModFunc(func(_ context.Context, o *RecentStickerTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m recentStickerMods) UpdatedAt(val time.Time) RecentStickerMod {
	return RecentStickerModFunc(func(_ context.Context, o *RecentStickerTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m recentStickerMods) UpdatedAtFunc(f func() time.Time) RecentStickerMod {
	return RecentStickerModFunc(func(_ context.Context, o *RecentStickerTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m recentStickerMods) UnsetUpdatedAt() RecentStickerMod {
	return RecentStickerModFunc(func(_ context.Context, o *RecentStickerTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m recentStickerMods) RandomUpdatedAt(f *faker.Faker) RecentStickerMod {
	return RecentStickerModFunc(func(_ context.Context, o *RecentStickerTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m recentStickerMods) WithParentsCascading() RecentStickerMod {
	return RecentStickerModFunc(func(ctx context.Context, o *RecentStickerTemplate) {
		if isDone, _ := recentStickerWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = recentStickerWithParentsCascadingCtx.WithValue(ctx, true)
	})
}
