// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	models "github.com/JasonKhew96/stickers_bot/models"
	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type StickerKeywordMod interface {
	Apply(context.Context, *StickerKeywordTemplate)
}

type StickerKeywordModFunc func(context.Context, *StickerKeywordTemplate)

func (f StickerKeywordModFunc) Apply(ctx context.Context, n *StickerKeywordTemplate) {
	f(ctx, n)
}

type StickerKeywordModSlice []StickerKeywordMod

func (mods StickerKeywordModSlice) Apply(ctx context.Context, n *StickerKeywordTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// StickerKeywordTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type StickerKeywordTemplate struct {
	StickerID func() int64
	KeywordID func() int64
	CreatedAt func() time.Time
	UpdatedAt func() time.Time

	r stickerKeywordR
	f *Factory

	alreadyPersisted bool
}

type stickerKeywordR struct {
	Keyword *stickerKeywordRKeywordR
	Sticker *stickerKeywordRStickerR
}

type stickerKeywordRKeywordR struct {
	o *KeywordTemplate
}
type stickerKeywordRStickerR struct {
	o *StickerTemplate
}

// Apply mods to the StickerKeywordTemplate
func (o *StickerKeywordTemplate) Apply(ctx context.Context, mods ...StickerKeywordMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.StickerKeyword
// according to the relationships in the template. Nothing is inserted into the db
func (t StickerKeywordTemplate) setModelRels(o *models.StickerKeyword) {
	if t.r.Keyword != nil {
		rel := t.r.Keyword.o.Build()
		rel.R.StickerKeywords = append(rel.R.StickerKeywords, o)
		o.KeywordID = rel.ID // h2
		o.R.Keyword = rel
	}

	if t.r.Sticker != nil {
		rel := t.r.Sticker.o.Build()
		rel.R.StickerKeywords = append(rel.R.StickerKeywords, o)
		o.StickerID = rel.ID // h2
		o.R.Sticker = rel
	}
}

// BuildSetter returns an *models.StickerKeywordSetter
// this does nothing with the relationship templates
func (o StickerKeywordTemplate) BuildSetter() *models.StickerKeywordSetter {
	m := &models.StickerKeywordSetter{}

	if o.StickerID != nil {
		val := o.StickerID()
		m.StickerID = omit.From(val)
	}
	if o.KeywordID != nil {
		val := o.KeywordID()
		m.KeywordID = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.StickerKeywordSetter
// this does nothing with the relationship templates
func (o StickerKeywordTemplate) BuildManySetter(number int) []*models.StickerKeywordSetter {
	m := make([]*models.StickerKeywordSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.StickerKeyword
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use StickerKeywordTemplate.Create
func (o StickerKeywordTemplate) Build() *models.StickerKeyword {
	m := &models.StickerKeyword{}

	if o.StickerID != nil {
		m.StickerID = o.StickerID()
	}
	if o.KeywordID != nil {
		m.KeywordID = o.KeywordID()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.StickerKeywordSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use StickerKeywordTemplate.CreateMany
func (o StickerKeywordTemplate) BuildMany(number int) models.StickerKeywordSlice {
	m := make(models.StickerKeywordSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableStickerKeyword(m *models.StickerKeywordSetter) {
	if !(m.StickerID.IsValue()) {
		val := random_int64(nil)
		m.StickerID = omit.From(val)
	}
	if !(m.KeywordID.IsValue()) {
		val := random_int64(nil)
		m.KeywordID = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.StickerKeyword
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *StickerKeywordTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.StickerKeyword) error {
	var err error

	return err
}

// Create builds a stickerKeyword and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *StickerKeywordTemplate) Create(ctx context.Context, exec bob.Executor) (*models.StickerKeyword, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableStickerKeyword(opt)

	if o.r.Keyword == nil {
		StickerKeywordMods.WithNewKeyword().Apply(ctx, o)
	}

	var rel0 *models.Keyword

	if o.r.Keyword.o.alreadyPersisted {
		rel0 = o.r.Keyword.o.Build()
	} else {
		rel0, err = o.r.Keyword.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.KeywordID = omit.From(rel0.ID)

	if o.r.Sticker == nil {
		StickerKeywordMods.WithNewSticker().Apply(ctx, o)
	}

	var rel1 *models.Sticker

	if o.r.Sticker.o.alreadyPersisted {
		rel1 = o.r.Sticker.o.Build()
	} else {
		rel1, err = o.r.Sticker.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.StickerID = omit.From(rel1.ID)

	m, err := models.StickerKeywords.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.Keyword = rel0
	m.R.Sticker = rel1

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a stickerKeyword and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *StickerKeywordTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.StickerKeyword {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a stickerKeyword and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *StickerKeywordTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.StickerKeyword {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple stickerKeywords and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o StickerKeywordTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.StickerKeywordSlice, error) {
	var err error
	m := make(models.StickerKeywordSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple stickerKeywords and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o StickerKeywordTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.StickerKeywordSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple stickerKeywords and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o StickerKeywordTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.StickerKeywordSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// StickerKeyword has methods that act as mods for the StickerKeywordTemplate
var StickerKeywordMods stickerKeywordMods

type stickerKeywordMods struct{}

func (m stickerKeywordMods) RandomizeAllColumns(f *faker.Faker) StickerKeywordMod {
	return StickerKeywordModSlice{
		StickerKeywordMods.RandomStickerID(f),
		StickerKeywordMods.RandomKeywordID(f),
		StickerKeywordMods.RandomCreatedAt(f),
		StickerKeywordMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m stickerKeywordMods) StickerID(val int64) StickerKeywordMod {
	return StickerKeywordModFunc(func(_ context.Context, o *StickerKeywordTemplate) {
		o.StickerID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m stickerKeywordMods) StickerIDFunc(f func() int64) StickerKeywordMod {
	return StickerKeywordModFunc(func(_ context.Context, o *StickerKeywordTemplate) {
		o.StickerID = f
	})
}

// Clear any values for the column
func (m stickerKeywordMods) UnsetStickerID() StickerKeywordMod {
	return StickerKeywordModFunc(func(_ context.Context, o *StickerKeywordTemplate) {
		o.StickerID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m stickerKeywordMods) RandomStickerID(f *faker.Faker) StickerKeywordMod {
	return StickerKeywordModFunc(func(_ context.Context, o *StickerKeywordTemplate) {
		o.StickerID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m stickerKeywordMods) KeywordID(val int64) StickerKeywordMod {
	return StickerKeywordModFunc(func(_ context.Context, o *StickerKeywordTemplate) {
		o.KeywordID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m stickerKeywordMods) KeywordIDFunc(f func() int64) StickerKeywordMod {
	return StickerKeywordModFunc(func(_ context.Context, o *StickerKeywordTemplate) {
		o.KeywordID = f
	})
}

// Clear any values for the column
func (m stickerKeywordMods) UnsetKeywordID() StickerKeywordMod {
	return StickerKeywordModFunc(func(_ context.Context, o *StickerKeywordTemplate) {
		o.KeywordID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m stickerKeywordMods) RandomKeywordID(f *faker.Faker) StickerKeywordMod {
	return StickerKeywordModFunc(func(_ context.Context, o *StickerKeywordTemplate) {
		o.KeywordID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m stickerKeywordMods) CreatedAt(val time.Time) StickerKeywordMod {
	return StickerKeywordModFunc(func(_ context.Context, o *StickerKeywordTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m stickerKeywordMods) CreatedAtFunc(f func() time.Time) StickerKeywordMod {
	return StickerKeywordModFunc(func(_ context.Context, o *StickerKeywordTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m stickerKeywordMods) UnsetCreatedAt() StickerKeywordMod {
	return StickerKeywordModFunc(func(_ context.Context, o *StickerKeywordTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m stickerKeywordMods) RandomCreatedAt(f *faker.Faker) StickerKeywordMod {
	return StickerKeywordModFunc(func(_ context.Context, o *StickerKeywordTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m stickerKeywordMods) UpdatedAt(val time.Time) StickerKeywordMod {
	return StickerKeywordModFunc(func(_ context.Context, o *StickerKeywordTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m stickerKeywordMods) UpdatedAtFunc(f func() time.Time) StickerKeywordMod {
	return StickerKeywordModFunc(func(_ context.Context, o *StickerKeywordTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m stickerKeywordMods) UnsetUpdatedAt() StickerKeywordMod {
	return StickerKeywordModFunc(func(_ context.Context, o *StickerKeywordTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m stickerKeywordMods) RandomUpdatedAt(f *faker.Faker) StickerKeywordMod {
	return StickerKeywordModFunc(func(_ context.Context, o *StickerKeywordTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m stickerKeywordMods) WithParentsCascading() StickerKeywordMod {
	return StickerKeywordModFunc(func(ctx context.Context, o *StickerKeywordTemplate) {
		if isDone, _ := stickerKeywordWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = stickerKeywordWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewKeywordWithContext(ctx, KeywordMods.WithParentsCascading())
			m.WithKeyword(related).Apply(ctx, o)
		}
		{

			related := o.f.NewStickerWithContext(ctx, StickerMods.WithParentsCascading())
			m.WithSticker(related).Apply(ctx, o)
		}
	})
}

func (m stickerKeywordMods) WithKeyword(rel *KeywordTemplate) StickerKeywordMod {
	return StickerKeywordModFunc(func(ctx context.Context, o *StickerKeywordTemplate) {
		o.r.Keyword = &stickerKeywordRKeywordR{
			o: rel,
		}
	})
}

func (m stickerKeywordMods) WithNewKeyword(mods ...KeywordMod) StickerKeywordMod {
	return StickerKeywordModFunc(func(ctx context.Context, o *StickerKeywordTemplate) {
		related := o.f.NewKeywordWithContext(ctx, mods...)

		m.WithKeyword(related).Apply(ctx, o)
	})
}

func (m stickerKeywordMods) WithExistingKeyword(em *models.Keyword) StickerKeywordMod {
	return StickerKeywordModFunc(func(ctx context.Context, o *StickerKeywordTemplate) {
		o.r.Keyword = &stickerKeywordRKeywordR{
			o: o.f.FromExistingKeyword(em),
		}
	})
}

func (m stickerKeywordMods) WithoutKeyword() StickerKeywordMod {
	return StickerKeywordModFunc(func(ctx context.Context, o *StickerKeywordTemplate) {
		o.r.Keyword = nil
	})
}

func (m stickerKeywordMods) WithSticker(rel *StickerTemplate) StickerKeywordMod {
	return StickerKeywordModFunc(func(ctx context.Context, o *StickerKeywordTemplate) {
		o.r.Sticker = &stickerKeywordRStickerR{
			o: rel,
		}
	})
}

func (m stickerKeywordMods) WithNewSticker(mods ...StickerMod) StickerKeywordMod {
	return StickerKeywordModFunc(func(ctx context.Context, o *StickerKeywordTemplate) {
		related := o.f.NewStickerWithContext(ctx, mods...)

		m.WithSticker(related).Apply(ctx, o)
	})
}

func (m stickerKeywordMods) WithExistingSticker(em *models.Sticker) StickerKeywordMod {
	return StickerKeywordModFunc(func(ctx context.Context, o *StickerKeywordTemplate) {
		o.r.Sticker = &stickerKeywordRStickerR{
			o: o.f.FromExistingSticker(em),
		}
	})
}

func (m stickerKeywordMods) WithoutSticker() StickerKeywordMod {
	return StickerKeywordModFunc(func(ctx context.Context, o *StickerKeywordTemplate) {
		o.r.Sticker = nil
	})
}
