// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	models "github.com/JasonKhew96/stickers_bot/models"
	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type StickerMod interface {
	Apply(context.Context, *StickerTemplate)
}

type StickerModFunc func(context.Context, *StickerTemplate)

func (f StickerModFunc) Apply(ctx context.Context, n *StickerTemplate) {
	f(ctx, n)
}

type StickerModSlice []StickerMod

func (mods StickerModSlice) Apply(ctx context.Context, n *StickerTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// StickerTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type StickerTemplate struct {
	ID          func() int64
	FileID      func() string
	StickerType func() string
	CreatedAt   func() time.Time
	UpdatedAt   func() time.Time

	r stickerR
	f *Factory

	alreadyPersisted bool
}

type stickerR struct {
	StickerKeywords []*stickerRStickerKeywordsR
}

type stickerRStickerKeywordsR struct {
	number int
	o      *StickerKeywordTemplate
}

// Apply mods to the StickerTemplate
func (o *StickerTemplate) Apply(ctx context.Context, mods ...StickerMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Sticker
// according to the relationships in the template. Nothing is inserted into the db
func (t StickerTemplate) setModelRels(o *models.Sticker) {
	if t.r.StickerKeywords != nil {
		rel := models.StickerKeywordSlice{}
		for _, r := range t.r.StickerKeywords {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.StickerID = o.ID // h2
				rel.R.Sticker = o
			}
			rel = append(rel, related...)
		}
		o.R.StickerKeywords = rel
	}
}

// BuildSetter returns an *models.StickerSetter
// this does nothing with the relationship templates
func (o StickerTemplate) BuildSetter() *models.StickerSetter {
	m := &models.StickerSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.FileID != nil {
		val := o.FileID()
		m.FileID = omit.From(val)
	}
	if o.StickerType != nil {
		val := o.StickerType()
		m.StickerType = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.StickerSetter
// this does nothing with the relationship templates
func (o StickerTemplate) BuildManySetter(number int) []*models.StickerSetter {
	m := make([]*models.StickerSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Sticker
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use StickerTemplate.Create
func (o StickerTemplate) Build() *models.Sticker {
	m := &models.Sticker{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.FileID != nil {
		m.FileID = o.FileID()
	}
	if o.StickerType != nil {
		m.StickerType = o.StickerType()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.StickerSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use StickerTemplate.CreateMany
func (o StickerTemplate) BuildMany(number int) models.StickerSlice {
	m := make(models.StickerSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableSticker(m *models.StickerSetter) {
	if !(m.FileID.IsValue()) {
		val := random_string(nil)
		m.FileID = omit.From(val)
	}
	if !(m.StickerType.IsValue()) {
		val := random_string(nil)
		m.StickerType = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Sticker
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *StickerTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Sticker) error {
	var err error

	isStickerKeywordsDone, _ := stickerRelStickerKeywordsCtx.Value(ctx)
	if !isStickerKeywordsDone && o.r.StickerKeywords != nil {
		ctx = stickerRelStickerKeywordsCtx.WithValue(ctx, true)
		for _, r := range o.r.StickerKeywords {
			if r.o.alreadyPersisted {
				m.R.StickerKeywords = append(m.R.StickerKeywords, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachStickerKeywords(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a sticker and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *StickerTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Sticker, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableSticker(opt)

	m, err := models.Stickers.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a sticker and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *StickerTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Sticker {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a sticker and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *StickerTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Sticker {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple stickers and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o StickerTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.StickerSlice, error) {
	var err error
	m := make(models.StickerSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple stickers and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o StickerTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.StickerSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple stickers and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o StickerTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.StickerSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Sticker has methods that act as mods for the StickerTemplate
var StickerMods stickerMods

type stickerMods struct{}

func (m stickerMods) RandomizeAllColumns(f *faker.Faker) StickerMod {
	return StickerModSlice{
		StickerMods.RandomID(f),
		StickerMods.RandomFileID(f),
		StickerMods.RandomStickerType(f),
		StickerMods.RandomCreatedAt(f),
		StickerMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m stickerMods) ID(val int64) StickerMod {
	return StickerModFunc(func(_ context.Context, o *StickerTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m stickerMods) IDFunc(f func() int64) StickerMod {
	return StickerModFunc(func(_ context.Context, o *StickerTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m stickerMods) UnsetID() StickerMod {
	return StickerModFunc(func(_ context.Context, o *StickerTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m stickerMods) RandomID(f *faker.Faker) StickerMod {
	return StickerModFunc(func(_ context.Context, o *StickerTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m stickerMods) FileID(val string) StickerMod {
	return StickerModFunc(func(_ context.Context, o *StickerTemplate) {
		o.FileID = func() string { return val }
	})
}

// Set the Column from the function
func (m stickerMods) FileIDFunc(f func() string) StickerMod {
	return StickerModFunc(func(_ context.Context, o *StickerTemplate) {
		o.FileID = f
	})
}

// Clear any values for the column
func (m stickerMods) UnsetFileID() StickerMod {
	return StickerModFunc(func(_ context.Context, o *StickerTemplate) {
		o.FileID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m stickerMods) RandomFileID(f *faker.Faker) StickerMod {
	return StickerModFunc(func(_ context.Context, o *StickerTemplate) {
		o.FileID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m stickerMods) StickerType(val string) StickerMod {
	return StickerModFunc(func(_ context.Context, o *StickerTemplate) {
		o.StickerType = func() string { return val }
	})
}

// Set the Column from the function
func (m stickerMods) StickerTypeFunc(f func() string) StickerMod {
	return StickerModFunc(func(_ context.Context, o *StickerTemplate) {
		o.StickerType = f
	})
}

// Clear any values for the column
func (m stickerMods) UnsetStickerType() StickerMod {
	return StickerModFunc(func(_ context.Context, o *StickerTemplate) {
		o.StickerType = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m stickerMods) RandomStickerType(f *faker.Faker) StickerMod {
	return StickerModFunc(func(_ context.Context, o *StickerTemplate) {
		o.StickerType = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m stickerMods) CreatedAt(val time.Time) StickerMod {
	return StickerModFunc(func(_ context.Context, o *StickerTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m stickerMods) CreatedAtFunc(f func() time.Time) StickerMod {
	return StickerModFunc(func(_ context.Context, o *StickerTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m stickerMods) UnsetCreatedAt() StickerMod {
	return StickerModFunc(func(_ context.Context, o *StickerTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m stickerMods) RandomCreatedAt(f *faker.Faker) StickerMod {
	return StickerModFunc(func(_ context.Context, o *StickerTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m stickerMods) UpdatedAt(val time.Time) StickerMod {
	return StickerModFunc(func(_ context.Context, o *StickerTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m stickerMods) UpdatedAtFunc(f func() time.Time) StickerMod {
	return StickerModFunc(func(_ context.Context, o *StickerTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m stickerMods) UnsetUpdatedAt() StickerMod {
	return StickerModFunc(func(_ context.Context, o *StickerTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m stickerMods) RandomUpdatedAt(f *faker.Faker) StickerMod {
	return StickerModFunc(func(_ context.Context, o *StickerTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m stickerMods) WithParentsCascading() StickerMod {
	return StickerModFunc(func(ctx context.Context, o *StickerTemplate) {
		if isDone, _ := stickerWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = stickerWithParentsCascadingCtx.WithValue(ctx, true)
	})
}

func (m stickerMods) WithStickerKeywords(number int, related *StickerKeywordTemplate) StickerMod {
	return StickerModFunc(func(ctx context.Context, o *StickerTemplate) {
		o.r.StickerKeywords = []*stickerRStickerKeywordsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m stickerMods) WithNewStickerKeywords(number int, mods ...StickerKeywordMod) StickerMod {
	return StickerModFunc(func(ctx context.Context, o *StickerTemplate) {
		related := o.f.NewStickerKeywordWithContext(ctx, mods...)
		m.WithStickerKeywords(number, related).Apply(ctx, o)
	})
}

func (m stickerMods) AddStickerKeywords(number int, related *StickerKeywordTemplate) StickerMod {
	return StickerModFunc(func(ctx context.Context, o *StickerTemplate) {
		o.r.StickerKeywords = append(o.r.StickerKeywords, &stickerRStickerKeywordsR{
			number: number,
			o:      related,
		})
	})
}

func (m stickerMods) AddNewStickerKeywords(number int, mods ...StickerKeywordMod) StickerMod {
	return StickerModFunc(func(ctx context.Context, o *StickerTemplate) {
		related := o.f.NewStickerKeywordWithContext(ctx, mods...)
		m.AddStickerKeywords(number, related).Apply(ctx, o)
	})
}

func (m stickerMods) AddExistingStickerKeywords(existingModels ...*models.StickerKeyword) StickerMod {
	return StickerModFunc(func(ctx context.Context, o *StickerTemplate) {
		for _, em := range existingModels {
			o.r.StickerKeywords = append(o.r.StickerKeywords, &stickerRStickerKeywordsR{
				o: o.f.FromExistingStickerKeyword(em),
			})
		}
	})
}

func (m stickerMods) WithoutStickerKeywords() StickerMod {
	return StickerModFunc(func(ctx context.Context, o *StickerTemplate) {
		o.r.StickerKeywords = nil
	})
}
