// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Keywords = Table[
	keywordColumns,
	keywordIndexes,
	keywordForeignKeys,
	keywordUniques,
	keywordChecks,
]{
	Schema: "",
	Name:   "keyword",
	Columns: keywordColumns{
		ID: column{
			Name:      "id",
			DBType:    "INTEGER",
			Default:   "auto_increment",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Keyword: column{
			Name:      "keyword",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "TIMESTAMP",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "TIMESTAMP",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: keywordIndexes{
		PKMainKeyword: index{
			Type: "pk",
			Name: "pk_main_keyword",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
		SqliteAutoindexKeyword1: index{
			Type: "u",
			Name: "sqlite_autoindex_keyword_1",
			Columns: []indexColumn{
				{
					Name:         "keyword",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_keyword",
		Columns: []string{"id"},
		Comment: "",
	},

	Uniques: keywordUniques{
		SqliteAutoindexKeyword1: constraint{
			Name:    "sqlite_autoindex_keyword_1",
			Columns: []string{"keyword"},
			Comment: "",
		},
	},

	Comment: "",
}

type keywordColumns struct {
	ID        column
	Keyword   column
	CreatedAt column
	UpdatedAt column
}

func (c keywordColumns) AsSlice() []column {
	return []column{
		c.ID, c.Keyword, c.CreatedAt, c.UpdatedAt,
	}
}

type keywordIndexes struct {
	PKMainKeyword           index
	SqliteAutoindexKeyword1 index
}

func (i keywordIndexes) AsSlice() []index {
	return []index{
		i.PKMainKeyword, i.SqliteAutoindexKeyword1,
	}
}

type keywordForeignKeys struct{}

func (f keywordForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type keywordUniques struct {
	SqliteAutoindexKeyword1 constraint
}

func (u keywordUniques) AsSlice() []constraint {
	return []constraint{
		u.SqliteAutoindexKeyword1,
	}
}

type keywordChecks struct{}

func (c keywordChecks) AsSlice() []check {
	return []check{}
}
