// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var RecentStickers = Table[
	recentStickerColumns,
	recentStickerIndexes,
	recentStickerForeignKeys,
	recentStickerUniques,
	recentStickerChecks,
]{
	Schema: "",
	Name:   "recent_sticker",
	Columns: recentStickerColumns{
		ID: column{
			Name:      "id",
			DBType:    "INTEGER",
			Default:   "auto_increment",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Recents: column{
			Name:      "recents",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "TIMESTAMP",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "TIMESTAMP",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: recentStickerIndexes{
		PKMainRecentSticker: index{
			Type: "pk",
			Name: "pk_main_recent_sticker",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_recent_sticker",
		Columns: []string{"id"},
		Comment: "",
	},

	Comment: "",
}

type recentStickerColumns struct {
	ID        column
	Recents   column
	CreatedAt column
	UpdatedAt column
}

func (c recentStickerColumns) AsSlice() []column {
	return []column{
		c.ID, c.Recents, c.CreatedAt, c.UpdatedAt,
	}
}

type recentStickerIndexes struct {
	PKMainRecentSticker index
}

func (i recentStickerIndexes) AsSlice() []index {
	return []index{
		i.PKMainRecentSticker,
	}
}

type recentStickerForeignKeys struct{}

func (f recentStickerForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type recentStickerUniques struct{}

func (u recentStickerUniques) AsSlice() []constraint {
	return []constraint{}
}

type recentStickerChecks struct{}

func (c recentStickerChecks) AsSlice() []check {
	return []check{}
}
