// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Stickers = Table[
	stickerColumns,
	stickerIndexes,
	stickerForeignKeys,
	stickerUniques,
	stickerChecks,
]{
	Schema: "",
	Name:   "sticker",
	Columns: stickerColumns{
		ID: column{
			Name:      "id",
			DBType:    "INTEGER",
			Default:   "auto_increment",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		FileID: column{
			Name:      "file_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		StickerType: column{
			Name:      "sticker_type",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "TIMESTAMP",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "TIMESTAMP",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: stickerIndexes{
		PKMainSticker: index{
			Type: "pk",
			Name: "pk_main_sticker",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
		SqliteAutoindexSticker2: index{
			Type: "u",
			Name: "sqlite_autoindex_sticker_2",
			Columns: []indexColumn{
				{
					Name:         "file_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
		SqliteAutoindexSticker1: index{
			Type: "u",
			Name: "sqlite_autoindex_sticker_1",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_sticker",
		Columns: []string{"id"},
		Comment: "",
	},

	Uniques: stickerUniques{
		SqliteAutoindexSticker2: constraint{
			Name:    "sqlite_autoindex_sticker_2",
			Columns: []string{"file_id"},
			Comment: "",
		},
		SqliteAutoindexSticker1: constraint{
			Name:    "sqlite_autoindex_sticker_1",
			Columns: []string{"id"},
			Comment: "",
		},
	},

	Comment: "",
}

type stickerColumns struct {
	ID          column
	FileID      column
	StickerType column
	CreatedAt   column
	UpdatedAt   column
}

func (c stickerColumns) AsSlice() []column {
	return []column{
		c.ID, c.FileID, c.StickerType, c.CreatedAt, c.UpdatedAt,
	}
}

type stickerIndexes struct {
	PKMainSticker           index
	SqliteAutoindexSticker2 index
	SqliteAutoindexSticker1 index
}

func (i stickerIndexes) AsSlice() []index {
	return []index{
		i.PKMainSticker, i.SqliteAutoindexSticker2, i.SqliteAutoindexSticker1,
	}
}

type stickerForeignKeys struct{}

func (f stickerForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type stickerUniques struct {
	SqliteAutoindexSticker2 constraint
	SqliteAutoindexSticker1 constraint
}

func (u stickerUniques) AsSlice() []constraint {
	return []constraint{
		u.SqliteAutoindexSticker2, u.SqliteAutoindexSticker1,
	}
}

type stickerChecks struct{}

func (c stickerChecks) AsSlice() []check {
	return []check{}
}
