// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var StickerKeywords = Table[
	stickerKeywordColumns,
	stickerKeywordIndexes,
	stickerKeywordForeignKeys,
	stickerKeywordUniques,
	stickerKeywordChecks,
]{
	Schema: "",
	Name:   "sticker_keyword",
	Columns: stickerKeywordColumns{
		StickerID: column{
			Name:      "sticker_id",
			DBType:    "INTEGER",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		KeywordID: column{
			Name:      "keyword_id",
			DBType:    "INTEGER",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "TIMESTAMP",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "TIMESTAMP",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: stickerKeywordIndexes{
		SqliteAutoindexStickerKeyword1: index{
			Type: "pk",
			Name: "sqlite_autoindex_sticker_keyword_1",
			Columns: []indexColumn{
				{
					Name:         "sticker_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "keyword_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_sticker_keyword",
		Columns: []string{"sticker_id", "keyword_id"},
		Comment: "",
	},
	ForeignKeys: stickerKeywordForeignKeys{
		FKStickerKeyword0: foreignKey{
			constraint: constraint{
				Name:    "fk_sticker_keyword_0",
				Columns: []string{"keyword_id"},
				Comment: "",
			},
			ForeignTable:   "keyword",
			ForeignColumns: []string{"id"},
		},
		FKStickerKeyword1: foreignKey{
			constraint: constraint{
				Name:    "fk_sticker_keyword_1",
				Columns: []string{"sticker_id"},
				Comment: "",
			},
			ForeignTable:   "sticker",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type stickerKeywordColumns struct {
	StickerID column
	KeywordID column
	CreatedAt column
	UpdatedAt column
}

func (c stickerKeywordColumns) AsSlice() []column {
	return []column{
		c.StickerID, c.KeywordID, c.CreatedAt, c.UpdatedAt,
	}
}

type stickerKeywordIndexes struct {
	SqliteAutoindexStickerKeyword1 index
}

func (i stickerKeywordIndexes) AsSlice() []index {
	return []index{
		i.SqliteAutoindexStickerKeyword1,
	}
}

type stickerKeywordForeignKeys struct {
	FKStickerKeyword0 foreignKey
	FKStickerKeyword1 foreignKey
}

func (f stickerKeywordForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKStickerKeyword0, f.FKStickerKeyword1,
	}
}

type stickerKeywordUniques struct{}

func (u stickerKeywordUniques) AsSlice() []constraint {
	return []constraint{}
}

type stickerKeywordChecks struct{}

func (c stickerKeywordChecks) AsSlice() []check {
	return []check{}
}
