// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var KeywordErrors = &keywordErrors{
	ErrUniquePkMainKeyword: &UniqueConstraintError{
		schema:  "",
		table:   "keyword",
		columns: []string{"id"},
		s:       "pk_main_keyword",
	},

	ErrUniqueSqliteAutoindexKeyword1: &UniqueConstraintError{
		schema:  "",
		table:   "keyword",
		columns: []string{"keyword"},
		s:       "sqlite_autoindex_keyword_1",
	},
}

type keywordErrors struct {
	ErrUniquePkMainKeyword *UniqueConstraintError

	ErrUniqueSqliteAutoindexKeyword1 *UniqueConstraintError
}
