// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var RecentStickerErrors = &recentStickerErrors{
	ErrUniquePkMainRecentSticker: &UniqueConstraintError{
		schema:  "",
		table:   "recent_sticker",
		columns: []string{"id"},
		s:       "pk_main_recent_sticker",
	},
}

type recentStickerErrors struct {
	ErrUniquePkMainRecentSticker *UniqueConstraintError
}
