// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var StickerErrors = &stickerErrors{
	ErrUniquePkMainSticker: &UniqueConstraintError{
		schema:  "",
		table:   "sticker",
		columns: []string{"id"},
		s:       "pk_main_sticker",
	},

	ErrUniqueSqliteAutoindexSticker2: &UniqueConstraintError{
		schema:  "",
		table:   "sticker",
		columns: []string{"file_id"},
		s:       "sqlite_autoindex_sticker_2",
	},

	ErrUniqueSqliteAutoindexSticker1: &UniqueConstraintError{
		schema:  "",
		table:   "sticker",
		columns: []string{"id"},
		s:       "sqlite_autoindex_sticker_1",
	},
}

type stickerErrors struct {
	ErrUniquePkMainSticker *UniqueConstraintError

	ErrUniqueSqliteAutoindexSticker2 *UniqueConstraintError

	ErrUniqueSqliteAutoindexSticker1 *UniqueConstraintError
}
