// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var StickerKeywordErrors = &stickerKeywordErrors{
	ErrUniquePkMainStickerKeyword: &UniqueConstraintError{
		schema:  "",
		table:   "sticker_keyword",
		columns: []string{"sticker_id", "keyword_id"},
		s:       "pk_main_sticker_keyword",
	},
}

type stickerKeywordErrors struct {
	ErrUniquePkMainStickerKeyword *UniqueConstraintError
}
