// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "github.com/stephenafamo/bob"

// Set the testDB to enable tests that use the database
var testDB bob.Transactor[bob.Tx]

// Make sure the type Keyword runs hooks after queries
var _ bob.HookableType = &Keyword{}

// Make sure the type RecentSticker runs hooks after queries
var _ bob.HookableType = &RecentSticker{}

// Make sure the type Sticker runs hooks after queries
var _ bob.HookableType = &Sticker{}

// Make sure the type StickerKeyword runs hooks after queries
var _ bob.HookableType = &StickerKeyword{}
