// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testKeywords(t *testing.T) {
	t.Parallel()

	query := Keywords()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testKeywordsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Keyword{}
	if err = randomize.Struct(seed, o, keywordDBTypes, true, keywordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keyword struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Keywords().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testKeywordsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Keyword{}
	if err = randomize.Struct(seed, o, keywordDBTypes, true, keywordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keyword struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Keywords().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Keywords().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testKeywordsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Keyword{}
	if err = randomize.Struct(seed, o, keywordDBTypes, true, keywordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keyword struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := KeywordSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Keywords().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testKeywordsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Keyword{}
	if err = randomize.Struct(seed, o, keywordDBTypes, true, keywordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keyword struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := KeywordExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Keyword exists: %s", err)
	}
	if !e {
		t.Errorf("Expected KeywordExists to return true, but got false.")
	}
}

func testKeywordsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Keyword{}
	if err = randomize.Struct(seed, o, keywordDBTypes, true, keywordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keyword struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	keywordFound, err := FindKeyword(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if keywordFound == nil {
		t.Error("want a record, got nil")
	}
}

func testKeywordsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Keyword{}
	if err = randomize.Struct(seed, o, keywordDBTypes, true, keywordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keyword struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Keywords().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testKeywordsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Keyword{}
	if err = randomize.Struct(seed, o, keywordDBTypes, true, keywordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keyword struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Keywords().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testKeywordsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	keywordOne := &Keyword{}
	keywordTwo := &Keyword{}
	if err = randomize.Struct(seed, keywordOne, keywordDBTypes, false, keywordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keyword struct: %s", err)
	}
	if err = randomize.Struct(seed, keywordTwo, keywordDBTypes, false, keywordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keyword struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = keywordOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = keywordTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Keywords().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testKeywordsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	keywordOne := &Keyword{}
	keywordTwo := &Keyword{}
	if err = randomize.Struct(seed, keywordOne, keywordDBTypes, false, keywordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keyword struct: %s", err)
	}
	if err = randomize.Struct(seed, keywordTwo, keywordDBTypes, false, keywordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keyword struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = keywordOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = keywordTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Keywords().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testKeywordsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Keyword{}
	if err = randomize.Struct(seed, o, keywordDBTypes, true, keywordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keyword struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Keywords().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testKeywordsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Keyword{}
	if err = randomize.Struct(seed, o, keywordDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Keyword struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(keywordColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Keywords().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testKeywordToManyStickerKeywords(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Keyword
	var b, c StickerKeyword

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, keywordDBTypes, true, keywordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keyword struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, stickerKeywordDBTypes, false, stickerKeywordColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, stickerKeywordDBTypes, false, stickerKeywordColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.KeywordID = a.ID
	c.KeywordID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.StickerKeywords().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.KeywordID == b.KeywordID {
			bFound = true
		}
		if v.KeywordID == c.KeywordID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := KeywordSlice{&a}
	if err = a.L.LoadStickerKeywords(ctx, tx, false, (*[]*Keyword)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.StickerKeywords); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.StickerKeywords = nil
	if err = a.L.LoadStickerKeywords(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.StickerKeywords); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testKeywordToManyAddOpStickerKeywords(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Keyword
	var b, c, d, e StickerKeyword

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, keywordDBTypes, false, strmangle.SetComplement(keywordPrimaryKeyColumns, keywordColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*StickerKeyword{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, stickerKeywordDBTypes, false, strmangle.SetComplement(stickerKeywordPrimaryKeyColumns, stickerKeywordColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*StickerKeyword{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddStickerKeywords(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.KeywordID {
			t.Error("foreign key was wrong value", a.ID, first.KeywordID)
		}
		if a.ID != second.KeywordID {
			t.Error("foreign key was wrong value", a.ID, second.KeywordID)
		}

		if first.R.Keyword != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Keyword != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.StickerKeywords[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.StickerKeywords[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.StickerKeywords().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testKeywordsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Keyword{}
	if err = randomize.Struct(seed, o, keywordDBTypes, true, keywordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keyword struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testKeywordsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Keyword{}
	if err = randomize.Struct(seed, o, keywordDBTypes, true, keywordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keyword struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := KeywordSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testKeywordsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Keyword{}
	if err = randomize.Struct(seed, o, keywordDBTypes, true, keywordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keyword struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Keywords().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	keywordDBTypes = map[string]string{`ID`: `INTEGER`, `Keyword`: `TEXT`, `CreatedAt`: `DATETIME`, `UpdatedAt`: `DATETIME`}
	_              = bytes.MinRead
)

func testKeywordsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(keywordPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(keywordAllColumns) == len(keywordPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Keyword{}
	if err = randomize.Struct(seed, o, keywordDBTypes, true, keywordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keyword struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Keywords().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, keywordDBTypes, true, keywordPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Keyword struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testKeywordsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(keywordAllColumns) == len(keywordPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Keyword{}
	if err = randomize.Struct(seed, o, keywordDBTypes, true, keywordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keyword struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Keywords().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, keywordDBTypes, true, keywordPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Keyword struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(keywordAllColumns, keywordPrimaryKeyColumns) {
		fields = keywordAllColumns
	} else {
		fields = strmangle.SetComplement(
			keywordAllColumns,
			keywordPrimaryKeyColumns,
		)
		fields = strmangle.SetComplement(fields, keywordGeneratedColumns)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := KeywordSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testKeywordsUpsert(t *testing.T) {
	t.Parallel()
	if len(keywordAllColumns) == len(keywordPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Keyword{}
	if err = randomize.Struct(seed, &o, keywordDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Keyword struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Keyword: %s", err)
	}

	count, err := Keywords().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, keywordDBTypes, false, keywordPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Keyword struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Keyword: %s", err)
	}

	count, err = Keywords().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
