// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// Keyword is an object representing the database table.
type Keyword struct {
	ID        int64     `db:"id,pk" `
	Keyword   string    `db:"keyword" `
	CreatedAt time.Time `db:"created_at" `
	UpdatedAt time.Time `db:"updated_at" `

	R keywordR `db:"-" `
}

// KeywordSlice is an alias for a slice of pointers to Keyword.
// This should almost always be used instead of []*Keyword.
type KeywordSlice []*Keyword

// Keywords contains methods to work with the keyword table
var Keywords = sqlite.NewTablex[*Keyword, KeywordSlice, *KeywordSetter]("", "keyword", buildKeywordColumns("keyword"))

// KeywordsQuery is a query on the keyword table
type KeywordsQuery = *sqlite.ViewQuery[*Keyword, KeywordSlice]

// keywordR is where relationships are stored.
type keywordR struct {
	StickerKeywords StickerKeywordSlice // fk_sticker_keyword_0
}

func buildKeywordColumns(alias string) keywordColumns {
	return keywordColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "keyword", "created_at", "updated_at",
		).WithParent("keyword"),
		tableAlias: alias,
		ID:         sqlite.Quote(alias, "id"),
		Keyword:    sqlite.Quote(alias, "keyword"),
		CreatedAt:  sqlite.Quote(alias, "created_at"),
		UpdatedAt:  sqlite.Quote(alias, "updated_at"),
	}
}

type keywordColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         sqlite.Expression
	Keyword    sqlite.Expression
	CreatedAt  sqlite.Expression
	UpdatedAt  sqlite.Expression
}

func (c keywordColumns) Alias() string {
	return c.tableAlias
}

func (keywordColumns) AliasedAs(alias string) keywordColumns {
	return buildKeywordColumns(alias)
}

// KeywordSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type KeywordSetter struct {
	ID        omit.Val[int64]     `db:"id,pk" `
	Keyword   omit.Val[string]    `db:"keyword" `
	CreatedAt omit.Val[time.Time] `db:"created_at" `
	UpdatedAt omit.Val[time.Time] `db:"updated_at" `
}

func (s KeywordSetter) SetColumns() []string {
	vals := make([]string, 0, 4)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Keyword.IsValue() {
		vals = append(vals, "keyword")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s KeywordSetter) Overwrite(t *Keyword) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Keyword.IsValue() {
		t.Keyword = s.Keyword.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *KeywordSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Keywords.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"id"}
		}

	}

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 0, 4)
		if s.ID.IsValue() {
			vals = append(vals, sqlite.Arg(s.ID.MustGet()))
		}

		if s.Keyword.IsValue() {
			vals = append(vals, sqlite.Arg(s.Keyword.MustGet()))
		}

		if s.CreatedAt.IsValue() {
			vals = append(vals, sqlite.Arg(s.CreatedAt.MustGet()))
		}

		if s.UpdatedAt.IsValue() {
			vals = append(vals, sqlite.Arg(s.UpdatedAt.MustGet()))
		}

		if len(vals) == 0 {
			vals = append(vals, sqlite.Arg(nil))
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s KeywordSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s KeywordSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 4)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if s.Keyword.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "keyword")...),
			sqlite.Arg(s.Keyword),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "created_at")...),
			sqlite.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "updated_at")...),
			sqlite.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindKeyword retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindKeyword(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*Keyword, error) {
	if len(cols) == 0 {
		return Keywords.Query(
			sm.Where(Keywords.Columns.ID.EQ(sqlite.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Keywords.Query(
		sm.Where(Keywords.Columns.ID.EQ(sqlite.Arg(IDPK))),
		sm.Columns(Keywords.Columns.Only(cols...)),
	).One(ctx, exec)
}

// KeywordExists checks the presence of a single record by primary key
func KeywordExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return Keywords.Query(
		sm.Where(Keywords.Columns.ID.EQ(sqlite.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Keyword is retrieved from the database
func (o *Keyword) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Keywords.AfterSelectHooks.RunHooks(ctx, exec, KeywordSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Keywords.AfterInsertHooks.RunHooks(ctx, exec, KeywordSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Keywords.AfterUpdateHooks.RunHooks(ctx, exec, KeywordSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Keywords.AfterDeleteHooks.RunHooks(ctx, exec, KeywordSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Keyword
func (o *Keyword) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *Keyword) pkEQ() dialect.Expression {
	return sqlite.Quote("keyword", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Keyword
func (o *Keyword) Update(ctx context.Context, exec bob.Executor, s *KeywordSetter) error {
	v, err := Keywords.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Keyword record with an executor
func (o *Keyword) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Keywords.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Keyword using the executor
func (o *Keyword) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Keywords.Query(
		sm.Where(Keywords.Columns.ID.EQ(sqlite.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after KeywordSlice is retrieved from the database
func (o KeywordSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Keywords.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Keywords.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Keywords.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Keywords.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o KeywordSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("keyword", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o KeywordSlice) copyMatchingRows(from ...*Keyword) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o KeywordSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Keywords.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Keyword:
				o.copyMatchingRows(retrieved)
			case []*Keyword:
				o.copyMatchingRows(retrieved...)
			case KeywordSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Keyword or a slice of Keyword
				// then run the AfterUpdateHooks on the slice
				_, err = Keywords.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o KeywordSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Keywords.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Keyword:
				o.copyMatchingRows(retrieved)
			case []*Keyword:
				o.copyMatchingRows(retrieved...)
			case KeywordSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Keyword or a slice of Keyword
				// then run the AfterDeleteHooks on the slice
				_, err = Keywords.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o KeywordSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals KeywordSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Keywords.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o KeywordSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Keywords.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o KeywordSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Keywords.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// StickerKeywords starts a query for related objects on sticker_keyword
func (o *Keyword) StickerKeywords(mods ...bob.Mod[*dialect.SelectQuery]) StickerKeywordsQuery {
	return StickerKeywords.Query(append(mods,
		sm.Where(StickerKeywords.Columns.KeywordID.EQ(sqlite.Arg(o.ID))),
	)...)
}

func (os KeywordSlice) StickerKeywords(mods ...bob.Mod[*dialect.SelectQuery]) StickerKeywordsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.ID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return StickerKeywords.Query(append(mods,
		sm.Where(sqlite.Group(StickerKeywords.Columns.KeywordID).OP("IN", PKArgExpr)),
	)...)
}

func insertKeywordStickerKeywords0(ctx context.Context, exec bob.Executor, stickerKeywords1 []*StickerKeywordSetter, keyword0 *Keyword) (StickerKeywordSlice, error) {
	for i := range stickerKeywords1 {
		stickerKeywords1[i].KeywordID = omit.From(keyword0.ID)
	}

	ret, err := StickerKeywords.Insert(bob.ToMods(stickerKeywords1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertKeywordStickerKeywords0: %w", err)
	}

	return ret, nil
}

func attachKeywordStickerKeywords0(ctx context.Context, exec bob.Executor, count int, stickerKeywords1 StickerKeywordSlice, keyword0 *Keyword) (StickerKeywordSlice, error) {
	setter := &StickerKeywordSetter{
		KeywordID: omit.From(keyword0.ID),
	}

	err := stickerKeywords1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachKeywordStickerKeywords0: %w", err)
	}

	return stickerKeywords1, nil
}

func (keyword0 *Keyword) InsertStickerKeywords(ctx context.Context, exec bob.Executor, related ...*StickerKeywordSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	stickerKeywords1, err := insertKeywordStickerKeywords0(ctx, exec, related, keyword0)
	if err != nil {
		return err
	}

	keyword0.R.StickerKeywords = append(keyword0.R.StickerKeywords, stickerKeywords1...)

	for _, rel := range stickerKeywords1 {
		rel.R.Keyword = keyword0
	}
	return nil
}

func (keyword0 *Keyword) AttachStickerKeywords(ctx context.Context, exec bob.Executor, related ...*StickerKeyword) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	stickerKeywords1 := StickerKeywordSlice(related)

	_, err = attachKeywordStickerKeywords0(ctx, exec, len(related), stickerKeywords1, keyword0)
	if err != nil {
		return err
	}

	keyword0.R.StickerKeywords = append(keyword0.R.StickerKeywords, stickerKeywords1...)

	for _, rel := range related {
		rel.R.Keyword = keyword0
	}

	return nil
}

type keywordWhere[Q sqlite.Filterable] struct {
	ID        sqlite.WhereMod[Q, int64]
	Keyword   sqlite.WhereMod[Q, string]
	CreatedAt sqlite.WhereMod[Q, time.Time]
	UpdatedAt sqlite.WhereMod[Q, time.Time]
}

func (keywordWhere[Q]) AliasedAs(alias string) keywordWhere[Q] {
	return buildKeywordWhere[Q](buildKeywordColumns(alias))
}

func buildKeywordWhere[Q sqlite.Filterable](cols keywordColumns) keywordWhere[Q] {
	return keywordWhere[Q]{
		ID:        sqlite.Where[Q, int64](cols.ID),
		Keyword:   sqlite.Where[Q, string](cols.Keyword),
		CreatedAt: sqlite.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt: sqlite.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *Keyword) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "StickerKeywords":
		rels, ok := retrieved.(StickerKeywordSlice)
		if !ok {
			return fmt.Errorf("keyword cannot load %T as %q", retrieved, name)
		}

		o.R.StickerKeywords = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Keyword = o
			}
		}
		return nil
	default:
		return fmt.Errorf("keyword has no relationship %q", name)
	}
}

type keywordPreloader struct{}

func buildKeywordPreloader() keywordPreloader {
	return keywordPreloader{}
}

type keywordThenLoader[Q orm.Loadable] struct {
	StickerKeywords func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildKeywordThenLoader[Q orm.Loadable]() keywordThenLoader[Q] {
	type StickerKeywordsLoadInterface interface {
		LoadStickerKeywords(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return keywordThenLoader[Q]{
		StickerKeywords: thenLoadBuilder[Q](
			"StickerKeywords",
			func(ctx context.Context, exec bob.Executor, retrieved StickerKeywordsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadStickerKeywords(ctx, exec, mods...)
			},
		),
	}
}

// LoadStickerKeywords loads the keyword's StickerKeywords into the .R struct
func (o *Keyword) LoadStickerKeywords(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.StickerKeywords = nil

	related, err := o.StickerKeywords(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Keyword = o
	}

	o.R.StickerKeywords = related
	return nil
}

// LoadStickerKeywords loads the keyword's StickerKeywords into the .R struct
func (os KeywordSlice) LoadStickerKeywords(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	stickerKeywords, err := os.StickerKeywords(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.StickerKeywords = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range stickerKeywords {

			if !(o.ID == rel.KeywordID) {
				continue
			}

			rel.R.Keyword = o

			o.R.StickerKeywords = append(o.R.StickerKeywords, rel)
		}
	}

	return nil
}

type keywordJoins[Q dialect.Joinable] struct {
	typ             string
	StickerKeywords modAs[Q, stickerKeywordColumns]
}

func (j keywordJoins[Q]) aliasedAs(alias string) keywordJoins[Q] {
	return buildKeywordJoins[Q](buildKeywordColumns(alias), j.typ)
}

func buildKeywordJoins[Q dialect.Joinable](cols keywordColumns, typ string) keywordJoins[Q] {
	return keywordJoins[Q]{
		typ: typ,
		StickerKeywords: modAs[Q, stickerKeywordColumns]{
			c: StickerKeywords.Columns,
			f: func(to stickerKeywordColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, StickerKeywords.Name().As(to.Alias())).On(
						to.KeywordID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
