// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
)

// RecentSticker is an object representing the database table.
type RecentSticker struct {
	ID        int64            `db:"id,pk" `
	Recents   null.Val[string] `db:"recents" `
	CreatedAt time.Time        `db:"created_at" `
	UpdatedAt time.Time        `db:"updated_at" `
}

// RecentStickerSlice is an alias for a slice of pointers to RecentSticker.
// This should almost always be used instead of []*RecentSticker.
type RecentStickerSlice []*RecentSticker

// RecentStickers contains methods to work with the recent_sticker table
var RecentStickers = sqlite.NewTablex[*RecentSticker, RecentStickerSlice, *RecentStickerSetter]("", "recent_sticker", buildRecentStickerColumns("recent_sticker"))

// RecentStickersQuery is a query on the recent_sticker table
type RecentStickersQuery = *sqlite.ViewQuery[*RecentSticker, RecentStickerSlice]

func buildRecentStickerColumns(alias string) recentStickerColumns {
	return recentStickerColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "recents", "created_at", "updated_at",
		).WithParent("recent_sticker"),
		tableAlias: alias,
		ID:         sqlite.Quote(alias, "id"),
		Recents:    sqlite.Quote(alias, "recents"),
		CreatedAt:  sqlite.Quote(alias, "created_at"),
		UpdatedAt:  sqlite.Quote(alias, "updated_at"),
	}
}

type recentStickerColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         sqlite.Expression
	Recents    sqlite.Expression
	CreatedAt  sqlite.Expression
	UpdatedAt  sqlite.Expression
}

func (c recentStickerColumns) Alias() string {
	return c.tableAlias
}

func (recentStickerColumns) AliasedAs(alias string) recentStickerColumns {
	return buildRecentStickerColumns(alias)
}

// RecentStickerSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type RecentStickerSetter struct {
	ID        omit.Val[int64]      `db:"id,pk" `
	Recents   omitnull.Val[string] `db:"recents" `
	CreatedAt omit.Val[time.Time]  `db:"created_at" `
	UpdatedAt omit.Val[time.Time]  `db:"updated_at" `
}

func (s RecentStickerSetter) SetColumns() []string {
	vals := make([]string, 0, 4)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if !s.Recents.IsUnset() {
		vals = append(vals, "recents")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s RecentStickerSetter) Overwrite(t *RecentSticker) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if !s.Recents.IsUnset() {
		t.Recents = s.Recents.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *RecentStickerSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return RecentStickers.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"id"}
		}

	}

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 0, 4)
		if s.ID.IsValue() {
			vals = append(vals, sqlite.Arg(s.ID.MustGet()))
		}

		if !s.Recents.IsUnset() {
			vals = append(vals, sqlite.Arg(s.Recents.MustGetNull()))
		}

		if s.CreatedAt.IsValue() {
			vals = append(vals, sqlite.Arg(s.CreatedAt.MustGet()))
		}

		if s.UpdatedAt.IsValue() {
			vals = append(vals, sqlite.Arg(s.UpdatedAt.MustGet()))
		}

		if len(vals) == 0 {
			vals = append(vals, sqlite.Arg(nil))
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s RecentStickerSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s RecentStickerSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 4)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if !s.Recents.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "recents")...),
			sqlite.Arg(s.Recents),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "created_at")...),
			sqlite.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "updated_at")...),
			sqlite.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindRecentSticker retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindRecentSticker(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*RecentSticker, error) {
	if len(cols) == 0 {
		return RecentStickers.Query(
			sm.Where(RecentStickers.Columns.ID.EQ(sqlite.Arg(IDPK))),
		).One(ctx, exec)
	}

	return RecentStickers.Query(
		sm.Where(RecentStickers.Columns.ID.EQ(sqlite.Arg(IDPK))),
		sm.Columns(RecentStickers.Columns.Only(cols...)),
	).One(ctx, exec)
}

// RecentStickerExists checks the presence of a single record by primary key
func RecentStickerExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return RecentStickers.Query(
		sm.Where(RecentStickers.Columns.ID.EQ(sqlite.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after RecentSticker is retrieved from the database
func (o *RecentSticker) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = RecentStickers.AfterSelectHooks.RunHooks(ctx, exec, RecentStickerSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = RecentStickers.AfterInsertHooks.RunHooks(ctx, exec, RecentStickerSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = RecentStickers.AfterUpdateHooks.RunHooks(ctx, exec, RecentStickerSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = RecentStickers.AfterDeleteHooks.RunHooks(ctx, exec, RecentStickerSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the RecentSticker
func (o *RecentSticker) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *RecentSticker) pkEQ() dialect.Expression {
	return sqlite.Quote("recent_sticker", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the RecentSticker
func (o *RecentSticker) Update(ctx context.Context, exec bob.Executor, s *RecentStickerSetter) error {
	v, err := RecentStickers.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single RecentSticker record with an executor
func (o *RecentSticker) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := RecentStickers.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the RecentSticker using the executor
func (o *RecentSticker) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := RecentStickers.Query(
		sm.Where(RecentStickers.Columns.ID.EQ(sqlite.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after RecentStickerSlice is retrieved from the database
func (o RecentStickerSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = RecentStickers.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = RecentStickers.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = RecentStickers.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = RecentStickers.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o RecentStickerSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("recent_sticker", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o RecentStickerSlice) copyMatchingRows(from ...*RecentSticker) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o RecentStickerSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return RecentStickers.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *RecentSticker:
				o.copyMatchingRows(retrieved)
			case []*RecentSticker:
				o.copyMatchingRows(retrieved...)
			case RecentStickerSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a RecentSticker or a slice of RecentSticker
				// then run the AfterUpdateHooks on the slice
				_, err = RecentStickers.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o RecentStickerSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return RecentStickers.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *RecentSticker:
				o.copyMatchingRows(retrieved)
			case []*RecentSticker:
				o.copyMatchingRows(retrieved...)
			case RecentStickerSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a RecentSticker or a slice of RecentSticker
				// then run the AfterDeleteHooks on the slice
				_, err = RecentStickers.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o RecentStickerSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals RecentStickerSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := RecentStickers.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o RecentStickerSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := RecentStickers.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o RecentStickerSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := RecentStickers.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type recentStickerWhere[Q sqlite.Filterable] struct {
	ID        sqlite.WhereMod[Q, int64]
	Recents   sqlite.WhereNullMod[Q, string]
	CreatedAt sqlite.WhereMod[Q, time.Time]
	UpdatedAt sqlite.WhereMod[Q, time.Time]
}

func (recentStickerWhere[Q]) AliasedAs(alias string) recentStickerWhere[Q] {
	return buildRecentStickerWhere[Q](buildRecentStickerColumns(alias))
}

func buildRecentStickerWhere[Q sqlite.Filterable](cols recentStickerColumns) recentStickerWhere[Q] {
	return recentStickerWhere[Q]{
		ID:        sqlite.Where[Q, int64](cols.ID),
		Recents:   sqlite.WhereNull[Q, string](cols.Recents),
		CreatedAt: sqlite.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt: sqlite.Where[Q, time.Time](cols.UpdatedAt),
	}
}
