// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// StickerKeyword is an object representing the database table.
type StickerKeyword struct {
	StickerID int64     `db:"sticker_id,pk" `
	KeywordID int64     `db:"keyword_id,pk" `
	CreatedAt time.Time `db:"created_at" `
	UpdatedAt time.Time `db:"updated_at" `

	R stickerKeywordR `db:"-" `
}

// StickerKeywordSlice is an alias for a slice of pointers to StickerKeyword.
// This should almost always be used instead of []*StickerKeyword.
type StickerKeywordSlice []*StickerKeyword

// StickerKeywords contains methods to work with the sticker_keyword table
var StickerKeywords = sqlite.NewTablex[*StickerKeyword, StickerKeywordSlice, *StickerKeywordSetter]("", "sticker_keyword", buildStickerKeywordColumns("sticker_keyword"))

// StickerKeywordsQuery is a query on the sticker_keyword table
type StickerKeywordsQuery = *sqlite.ViewQuery[*StickerKeyword, StickerKeywordSlice]

// stickerKeywordR is where relationships are stored.
type stickerKeywordR struct {
	Keyword *Keyword // fk_sticker_keyword_0
	Sticker *Sticker // fk_sticker_keyword_1
}

func buildStickerKeywordColumns(alias string) stickerKeywordColumns {
	return stickerKeywordColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"sticker_id", "keyword_id", "created_at", "updated_at",
		).WithParent("sticker_keyword"),
		tableAlias: alias,
		StickerID:  sqlite.Quote(alias, "sticker_id"),
		KeywordID:  sqlite.Quote(alias, "keyword_id"),
		CreatedAt:  sqlite.Quote(alias, "created_at"),
		UpdatedAt:  sqlite.Quote(alias, "updated_at"),
	}
}

type stickerKeywordColumns struct {
	expr.ColumnsExpr
	tableAlias string
	StickerID  sqlite.Expression
	KeywordID  sqlite.Expression
	CreatedAt  sqlite.Expression
	UpdatedAt  sqlite.Expression
}

func (c stickerKeywordColumns) Alias() string {
	return c.tableAlias
}

func (stickerKeywordColumns) AliasedAs(alias string) stickerKeywordColumns {
	return buildStickerKeywordColumns(alias)
}

// StickerKeywordSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type StickerKeywordSetter struct {
	StickerID omit.Val[int64]     `db:"sticker_id,pk" `
	KeywordID omit.Val[int64]     `db:"keyword_id,pk" `
	CreatedAt omit.Val[time.Time] `db:"created_at" `
	UpdatedAt omit.Val[time.Time] `db:"updated_at" `
}

func (s StickerKeywordSetter) SetColumns() []string {
	vals := make([]string, 0, 4)
	if s.StickerID.IsValue() {
		vals = append(vals, "sticker_id")
	}
	if s.KeywordID.IsValue() {
		vals = append(vals, "keyword_id")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s StickerKeywordSetter) Overwrite(t *StickerKeyword) {
	if s.StickerID.IsValue() {
		t.StickerID = s.StickerID.MustGet()
	}
	if s.KeywordID.IsValue() {
		t.KeywordID = s.KeywordID.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *StickerKeywordSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return StickerKeywords.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"sticker_id", "keyword_id"}
		}

	}

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 0, 4)
		if s.StickerID.IsValue() {
			vals = append(vals, sqlite.Arg(s.StickerID.MustGet()))
		}

		if s.KeywordID.IsValue() {
			vals = append(vals, sqlite.Arg(s.KeywordID.MustGet()))
		}

		if s.CreatedAt.IsValue() {
			vals = append(vals, sqlite.Arg(s.CreatedAt.MustGet()))
		}

		if s.UpdatedAt.IsValue() {
			vals = append(vals, sqlite.Arg(s.UpdatedAt.MustGet()))
		}

		if len(vals) == 0 {
			vals = append(vals, sqlite.Arg(nil), sqlite.Arg(nil))
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s StickerKeywordSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s StickerKeywordSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 4)

	if s.StickerID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "sticker_id")...),
			sqlite.Arg(s.StickerID),
		}})
	}

	if s.KeywordID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "keyword_id")...),
			sqlite.Arg(s.KeywordID),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "created_at")...),
			sqlite.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "updated_at")...),
			sqlite.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindStickerKeyword retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindStickerKeyword(ctx context.Context, exec bob.Executor, StickerIDPK int64, KeywordIDPK int64, cols ...string) (*StickerKeyword, error) {
	if len(cols) == 0 {
		return StickerKeywords.Query(
			sm.Where(StickerKeywords.Columns.StickerID.EQ(sqlite.Arg(StickerIDPK))),
			sm.Where(StickerKeywords.Columns.KeywordID.EQ(sqlite.Arg(KeywordIDPK))),
		).One(ctx, exec)
	}

	return StickerKeywords.Query(
		sm.Where(StickerKeywords.Columns.StickerID.EQ(sqlite.Arg(StickerIDPK))),
		sm.Where(StickerKeywords.Columns.KeywordID.EQ(sqlite.Arg(KeywordIDPK))),
		sm.Columns(StickerKeywords.Columns.Only(cols...)),
	).One(ctx, exec)
}

// StickerKeywordExists checks the presence of a single record by primary key
func StickerKeywordExists(ctx context.Context, exec bob.Executor, StickerIDPK int64, KeywordIDPK int64) (bool, error) {
	return StickerKeywords.Query(
		sm.Where(StickerKeywords.Columns.StickerID.EQ(sqlite.Arg(StickerIDPK))),
		sm.Where(StickerKeywords.Columns.KeywordID.EQ(sqlite.Arg(KeywordIDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after StickerKeyword is retrieved from the database
func (o *StickerKeyword) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = StickerKeywords.AfterSelectHooks.RunHooks(ctx, exec, StickerKeywordSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = StickerKeywords.AfterInsertHooks.RunHooks(ctx, exec, StickerKeywordSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = StickerKeywords.AfterUpdateHooks.RunHooks(ctx, exec, StickerKeywordSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = StickerKeywords.AfterDeleteHooks.RunHooks(ctx, exec, StickerKeywordSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the StickerKeyword
func (o *StickerKeyword) primaryKeyVals() bob.Expression {
	return sqlite.ArgGroup(
		o.StickerID,
		o.KeywordID,
	)
}

func (o *StickerKeyword) pkEQ() dialect.Expression {
	return sqlite.Group(sqlite.Quote("sticker_keyword", "sticker_id"), sqlite.Quote("sticker_keyword", "keyword_id")).EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the StickerKeyword
func (o *StickerKeyword) Update(ctx context.Context, exec bob.Executor, s *StickerKeywordSetter) error {
	v, err := StickerKeywords.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single StickerKeyword record with an executor
func (o *StickerKeyword) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := StickerKeywords.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the StickerKeyword using the executor
func (o *StickerKeyword) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := StickerKeywords.Query(
		sm.Where(StickerKeywords.Columns.StickerID.EQ(sqlite.Arg(o.StickerID))),
		sm.Where(StickerKeywords.Columns.KeywordID.EQ(sqlite.Arg(o.KeywordID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after StickerKeywordSlice is retrieved from the database
func (o StickerKeywordSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = StickerKeywords.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = StickerKeywords.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = StickerKeywords.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = StickerKeywords.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o StickerKeywordSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Group(sqlite.Quote("sticker_keyword", "sticker_id"), sqlite.Quote("sticker_keyword", "keyword_id")).In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o StickerKeywordSlice) copyMatchingRows(from ...*StickerKeyword) {
	for i, old := range o {
		for _, new := range from {
			if new.StickerID != old.StickerID {
				continue
			}
			if new.KeywordID != old.KeywordID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o StickerKeywordSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return StickerKeywords.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *StickerKeyword:
				o.copyMatchingRows(retrieved)
			case []*StickerKeyword:
				o.copyMatchingRows(retrieved...)
			case StickerKeywordSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a StickerKeyword or a slice of StickerKeyword
				// then run the AfterUpdateHooks on the slice
				_, err = StickerKeywords.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o StickerKeywordSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return StickerKeywords.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *StickerKeyword:
				o.copyMatchingRows(retrieved)
			case []*StickerKeyword:
				o.copyMatchingRows(retrieved...)
			case StickerKeywordSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a StickerKeyword or a slice of StickerKeyword
				// then run the AfterDeleteHooks on the slice
				_, err = StickerKeywords.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o StickerKeywordSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals StickerKeywordSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := StickerKeywords.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o StickerKeywordSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := StickerKeywords.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o StickerKeywordSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := StickerKeywords.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Keyword starts a query for related objects on keyword
func (o *StickerKeyword) Keyword(mods ...bob.Mod[*dialect.SelectQuery]) KeywordsQuery {
	return Keywords.Query(append(mods,
		sm.Where(Keywords.Columns.ID.EQ(sqlite.Arg(o.KeywordID))),
	)...)
}

func (os StickerKeywordSlice) Keyword(mods ...bob.Mod[*dialect.SelectQuery]) KeywordsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.KeywordID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return Keywords.Query(append(mods,
		sm.Where(sqlite.Group(Keywords.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// Sticker starts a query for related objects on sticker
func (o *StickerKeyword) Sticker(mods ...bob.Mod[*dialect.SelectQuery]) StickersQuery {
	return Stickers.Query(append(mods,
		sm.Where(Stickers.Columns.ID.EQ(sqlite.Arg(o.StickerID))),
	)...)
}

func (os StickerKeywordSlice) Sticker(mods ...bob.Mod[*dialect.SelectQuery]) StickersQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.StickerID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return Stickers.Query(append(mods,
		sm.Where(sqlite.Group(Stickers.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachStickerKeywordKeyword0(ctx context.Context, exec bob.Executor, count int, stickerKeyword0 *StickerKeyword, keyword1 *Keyword) (*StickerKeyword, error) {
	setter := &StickerKeywordSetter{
		KeywordID: omit.From(keyword1.ID),
	}

	err := stickerKeyword0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachStickerKeywordKeyword0: %w", err)
	}

	return stickerKeyword0, nil
}

func (stickerKeyword0 *StickerKeyword) InsertKeyword(ctx context.Context, exec bob.Executor, related *KeywordSetter) error {
	var err error

	keyword1, err := Keywords.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachStickerKeywordKeyword0(ctx, exec, 1, stickerKeyword0, keyword1)
	if err != nil {
		return err
	}

	stickerKeyword0.R.Keyword = keyword1

	keyword1.R.StickerKeywords = append(keyword1.R.StickerKeywords, stickerKeyword0)

	return nil
}

func (stickerKeyword0 *StickerKeyword) AttachKeyword(ctx context.Context, exec bob.Executor, keyword1 *Keyword) error {
	var err error

	_, err = attachStickerKeywordKeyword0(ctx, exec, 1, stickerKeyword0, keyword1)
	if err != nil {
		return err
	}

	stickerKeyword0.R.Keyword = keyword1

	keyword1.R.StickerKeywords = append(keyword1.R.StickerKeywords, stickerKeyword0)

	return nil
}

func attachStickerKeywordSticker0(ctx context.Context, exec bob.Executor, count int, stickerKeyword0 *StickerKeyword, sticker1 *Sticker) (*StickerKeyword, error) {
	setter := &StickerKeywordSetter{
		StickerID: omit.From(sticker1.ID),
	}

	err := stickerKeyword0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachStickerKeywordSticker0: %w", err)
	}

	return stickerKeyword0, nil
}

func (stickerKeyword0 *StickerKeyword) InsertSticker(ctx context.Context, exec bob.Executor, related *StickerSetter) error {
	var err error

	sticker1, err := Stickers.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachStickerKeywordSticker0(ctx, exec, 1, stickerKeyword0, sticker1)
	if err != nil {
		return err
	}

	stickerKeyword0.R.Sticker = sticker1

	sticker1.R.StickerKeywords = append(sticker1.R.StickerKeywords, stickerKeyword0)

	return nil
}

func (stickerKeyword0 *StickerKeyword) AttachSticker(ctx context.Context, exec bob.Executor, sticker1 *Sticker) error {
	var err error

	_, err = attachStickerKeywordSticker0(ctx, exec, 1, stickerKeyword0, sticker1)
	if err != nil {
		return err
	}

	stickerKeyword0.R.Sticker = sticker1

	sticker1.R.StickerKeywords = append(sticker1.R.StickerKeywords, stickerKeyword0)

	return nil
}

type stickerKeywordWhere[Q sqlite.Filterable] struct {
	StickerID sqlite.WhereMod[Q, int64]
	KeywordID sqlite.WhereMod[Q, int64]
	CreatedAt sqlite.WhereMod[Q, time.Time]
	UpdatedAt sqlite.WhereMod[Q, time.Time]
}

func (stickerKeywordWhere[Q]) AliasedAs(alias string) stickerKeywordWhere[Q] {
	return buildStickerKeywordWhere[Q](buildStickerKeywordColumns(alias))
}

func buildStickerKeywordWhere[Q sqlite.Filterable](cols stickerKeywordColumns) stickerKeywordWhere[Q] {
	return stickerKeywordWhere[Q]{
		StickerID: sqlite.Where[Q, int64](cols.StickerID),
		KeywordID: sqlite.Where[Q, int64](cols.KeywordID),
		CreatedAt: sqlite.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt: sqlite.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *StickerKeyword) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Keyword":
		rel, ok := retrieved.(*Keyword)
		if !ok {
			return fmt.Errorf("stickerKeyword cannot load %T as %q", retrieved, name)
		}

		o.R.Keyword = rel

		if rel != nil {
			rel.R.StickerKeywords = StickerKeywordSlice{o}
		}
		return nil
	case "Sticker":
		rel, ok := retrieved.(*Sticker)
		if !ok {
			return fmt.Errorf("stickerKeyword cannot load %T as %q", retrieved, name)
		}

		o.R.Sticker = rel

		if rel != nil {
			rel.R.StickerKeywords = StickerKeywordSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("stickerKeyword has no relationship %q", name)
	}
}

type stickerKeywordPreloader struct {
	Keyword func(...sqlite.PreloadOption) sqlite.Preloader
	Sticker func(...sqlite.PreloadOption) sqlite.Preloader
}

func buildStickerKeywordPreloader() stickerKeywordPreloader {
	return stickerKeywordPreloader{
		Keyword: func(opts ...sqlite.PreloadOption) sqlite.Preloader {
			return sqlite.Preload[*Keyword, KeywordSlice](sqlite.PreloadRel{
				Name: "Keyword",
				Sides: []sqlite.PreloadSide{
					{
						From:        StickerKeywords,
						To:          Keywords,
						FromColumns: []string{"keyword_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Keywords.Columns.Names(), opts...)
		},
		Sticker: func(opts ...sqlite.PreloadOption) sqlite.Preloader {
			return sqlite.Preload[*Sticker, StickerSlice](sqlite.PreloadRel{
				Name: "Sticker",
				Sides: []sqlite.PreloadSide{
					{
						From:        StickerKeywords,
						To:          Stickers,
						FromColumns: []string{"sticker_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Stickers.Columns.Names(), opts...)
		},
	}
}

type stickerKeywordThenLoader[Q orm.Loadable] struct {
	Keyword func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Sticker func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildStickerKeywordThenLoader[Q orm.Loadable]() stickerKeywordThenLoader[Q] {
	type KeywordLoadInterface interface {
		LoadKeyword(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type StickerLoadInterface interface {
		LoadSticker(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return stickerKeywordThenLoader[Q]{
		Keyword: thenLoadBuilder[Q](
			"Keyword",
			func(ctx context.Context, exec bob.Executor, retrieved KeywordLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadKeyword(ctx, exec, mods...)
			},
		),
		Sticker: thenLoadBuilder[Q](
			"Sticker",
			func(ctx context.Context, exec bob.Executor, retrieved StickerLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadSticker(ctx, exec, mods...)
			},
		),
	}
}

// LoadKeyword loads the stickerKeyword's Keyword into the .R struct
func (o *StickerKeyword) LoadKeyword(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Keyword = nil

	related, err := o.Keyword(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.StickerKeywords = StickerKeywordSlice{o}

	o.R.Keyword = related
	return nil
}

// LoadKeyword loads the stickerKeyword's Keyword into the .R struct
func (os StickerKeywordSlice) LoadKeyword(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	keywords, err := os.Keyword(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range keywords {

			if !(o.KeywordID == rel.ID) {
				continue
			}

			rel.R.StickerKeywords = append(rel.R.StickerKeywords, o)

			o.R.Keyword = rel
			break
		}
	}

	return nil
}

// LoadSticker loads the stickerKeyword's Sticker into the .R struct
func (o *StickerKeyword) LoadSticker(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Sticker = nil

	related, err := o.Sticker(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.StickerKeywords = StickerKeywordSlice{o}

	o.R.Sticker = related
	return nil
}

// LoadSticker loads the stickerKeyword's Sticker into the .R struct
func (os StickerKeywordSlice) LoadSticker(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	stickers, err := os.Sticker(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range stickers {

			if !(o.StickerID == rel.ID) {
				continue
			}

			rel.R.StickerKeywords = append(rel.R.StickerKeywords, o)

			o.R.Sticker = rel
			break
		}
	}

	return nil
}

type stickerKeywordJoins[Q dialect.Joinable] struct {
	typ     string
	Keyword modAs[Q, keywordColumns]
	Sticker modAs[Q, stickerColumns]
}

func (j stickerKeywordJoins[Q]) aliasedAs(alias string) stickerKeywordJoins[Q] {
	return buildStickerKeywordJoins[Q](buildStickerKeywordColumns(alias), j.typ)
}

func buildStickerKeywordJoins[Q dialect.Joinable](cols stickerKeywordColumns, typ string) stickerKeywordJoins[Q] {
	return stickerKeywordJoins[Q]{
		typ: typ,
		Keyword: modAs[Q, keywordColumns]{
			c: Keywords.Columns,
			f: func(to keywordColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Keywords.Name().As(to.Alias())).On(
						to.ID.EQ(cols.KeywordID),
					))
				}

				return mods
			},
		},
		Sticker: modAs[Q, stickerColumns]{
			c: Stickers.Columns,
			f: func(to stickerColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Stickers.Name().As(to.Alias())).On(
						to.ID.EQ(cols.StickerID),
					))
				}

				return mods
			},
		},
	}
}
