// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// Sticker is an object representing the database table.
type Sticker struct {
	ID          int64     `db:"id,pk" `
	FileID      string    `db:"file_id" `
	StickerType string    `db:"sticker_type" `
	CreatedAt   time.Time `db:"created_at" `
	UpdatedAt   time.Time `db:"updated_at" `

	R stickerR `db:"-" `
}

// StickerSlice is an alias for a slice of pointers to Sticker.
// This should almost always be used instead of []*Sticker.
type StickerSlice []*Sticker

// Stickers contains methods to work with the sticker table
var Stickers = sqlite.NewTablex[*Sticker, StickerSlice, *StickerSetter]("", "sticker", buildStickerColumns("sticker"))

// StickersQuery is a query on the sticker table
type StickersQuery = *sqlite.ViewQuery[*Sticker, StickerSlice]

// stickerR is where relationships are stored.
type stickerR struct {
	StickerKeywords StickerKeywordSlice // fk_sticker_keyword_1
}

func buildStickerColumns(alias string) stickerColumns {
	return stickerColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "file_id", "sticker_type", "created_at", "updated_at",
		).WithParent("sticker"),
		tableAlias:  alias,
		ID:          sqlite.Quote(alias, "id"),
		FileID:      sqlite.Quote(alias, "file_id"),
		StickerType: sqlite.Quote(alias, "sticker_type"),
		CreatedAt:   sqlite.Quote(alias, "created_at"),
		UpdatedAt:   sqlite.Quote(alias, "updated_at"),
	}
}

type stickerColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ID          sqlite.Expression
	FileID      sqlite.Expression
	StickerType sqlite.Expression
	CreatedAt   sqlite.Expression
	UpdatedAt   sqlite.Expression
}

func (c stickerColumns) Alias() string {
	return c.tableAlias
}

func (stickerColumns) AliasedAs(alias string) stickerColumns {
	return buildStickerColumns(alias)
}

// StickerSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type StickerSetter struct {
	ID          omit.Val[int64]     `db:"id,pk" `
	FileID      omit.Val[string]    `db:"file_id" `
	StickerType omit.Val[string]    `db:"sticker_type" `
	CreatedAt   omit.Val[time.Time] `db:"created_at" `
	UpdatedAt   omit.Val[time.Time] `db:"updated_at" `
}

func (s StickerSetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.FileID.IsValue() {
		vals = append(vals, "file_id")
	}
	if s.StickerType.IsValue() {
		vals = append(vals, "sticker_type")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s StickerSetter) Overwrite(t *Sticker) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.FileID.IsValue() {
		t.FileID = s.FileID.MustGet()
	}
	if s.StickerType.IsValue() {
		t.StickerType = s.StickerType.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *StickerSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Stickers.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"id"}
		}

	}

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 0, 5)
		if s.ID.IsValue() {
			vals = append(vals, sqlite.Arg(s.ID.MustGet()))
		}

		if s.FileID.IsValue() {
			vals = append(vals, sqlite.Arg(s.FileID.MustGet()))
		}

		if s.StickerType.IsValue() {
			vals = append(vals, sqlite.Arg(s.StickerType.MustGet()))
		}

		if s.CreatedAt.IsValue() {
			vals = append(vals, sqlite.Arg(s.CreatedAt.MustGet()))
		}

		if s.UpdatedAt.IsValue() {
			vals = append(vals, sqlite.Arg(s.UpdatedAt.MustGet()))
		}

		if len(vals) == 0 {
			vals = append(vals, sqlite.Arg(nil))
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s StickerSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s StickerSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if s.FileID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "file_id")...),
			sqlite.Arg(s.FileID),
		}})
	}

	if s.StickerType.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "sticker_type")...),
			sqlite.Arg(s.StickerType),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "created_at")...),
			sqlite.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "updated_at")...),
			sqlite.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindSticker retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindSticker(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*Sticker, error) {
	if len(cols) == 0 {
		return Stickers.Query(
			sm.Where(Stickers.Columns.ID.EQ(sqlite.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Stickers.Query(
		sm.Where(Stickers.Columns.ID.EQ(sqlite.Arg(IDPK))),
		sm.Columns(Stickers.Columns.Only(cols...)),
	).One(ctx, exec)
}

// StickerExists checks the presence of a single record by primary key
func StickerExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return Stickers.Query(
		sm.Where(Stickers.Columns.ID.EQ(sqlite.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Sticker is retrieved from the database
func (o *Sticker) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Stickers.AfterSelectHooks.RunHooks(ctx, exec, StickerSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Stickers.AfterInsertHooks.RunHooks(ctx, exec, StickerSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Stickers.AfterUpdateHooks.RunHooks(ctx, exec, StickerSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Stickers.AfterDeleteHooks.RunHooks(ctx, exec, StickerSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Sticker
func (o *Sticker) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *Sticker) pkEQ() dialect.Expression {
	return sqlite.Quote("sticker", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Sticker
func (o *Sticker) Update(ctx context.Context, exec bob.Executor, s *StickerSetter) error {
	v, err := Stickers.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Sticker record with an executor
func (o *Sticker) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Stickers.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Sticker using the executor
func (o *Sticker) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Stickers.Query(
		sm.Where(Stickers.Columns.ID.EQ(sqlite.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after StickerSlice is retrieved from the database
func (o StickerSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Stickers.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Stickers.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Stickers.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Stickers.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o StickerSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("sticker", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o StickerSlice) copyMatchingRows(from ...*Sticker) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o StickerSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Stickers.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Sticker:
				o.copyMatchingRows(retrieved)
			case []*Sticker:
				o.copyMatchingRows(retrieved...)
			case StickerSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Sticker or a slice of Sticker
				// then run the AfterUpdateHooks on the slice
				_, err = Stickers.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o StickerSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Stickers.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Sticker:
				o.copyMatchingRows(retrieved)
			case []*Sticker:
				o.copyMatchingRows(retrieved...)
			case StickerSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Sticker or a slice of Sticker
				// then run the AfterDeleteHooks on the slice
				_, err = Stickers.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o StickerSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals StickerSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Stickers.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o StickerSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Stickers.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o StickerSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Stickers.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// StickerKeywords starts a query for related objects on sticker_keyword
func (o *Sticker) StickerKeywords(mods ...bob.Mod[*dialect.SelectQuery]) StickerKeywordsQuery {
	return StickerKeywords.Query(append(mods,
		sm.Where(StickerKeywords.Columns.StickerID.EQ(sqlite.Arg(o.ID))),
	)...)
}

func (os StickerSlice) StickerKeywords(mods ...bob.Mod[*dialect.SelectQuery]) StickerKeywordsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.ID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return StickerKeywords.Query(append(mods,
		sm.Where(sqlite.Group(StickerKeywords.Columns.StickerID).OP("IN", PKArgExpr)),
	)...)
}

func insertStickerStickerKeywords0(ctx context.Context, exec bob.Executor, stickerKeywords1 []*StickerKeywordSetter, sticker0 *Sticker) (StickerKeywordSlice, error) {
	for i := range stickerKeywords1 {
		stickerKeywords1[i].StickerID = omit.From(sticker0.ID)
	}

	ret, err := StickerKeywords.Insert(bob.ToMods(stickerKeywords1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertStickerStickerKeywords0: %w", err)
	}

	return ret, nil
}

func attachStickerStickerKeywords0(ctx context.Context, exec bob.Executor, count int, stickerKeywords1 StickerKeywordSlice, sticker0 *Sticker) (StickerKeywordSlice, error) {
	setter := &StickerKeywordSetter{
		StickerID: omit.From(sticker0.ID),
	}

	err := stickerKeywords1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachStickerStickerKeywords0: %w", err)
	}

	return stickerKeywords1, nil
}

func (sticker0 *Sticker) InsertStickerKeywords(ctx context.Context, exec bob.Executor, related ...*StickerKeywordSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	stickerKeywords1, err := insertStickerStickerKeywords0(ctx, exec, related, sticker0)
	if err != nil {
		return err
	}

	sticker0.R.StickerKeywords = append(sticker0.R.StickerKeywords, stickerKeywords1...)

	for _, rel := range stickerKeywords1 {
		rel.R.Sticker = sticker0
	}
	return nil
}

func (sticker0 *Sticker) AttachStickerKeywords(ctx context.Context, exec bob.Executor, related ...*StickerKeyword) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	stickerKeywords1 := StickerKeywordSlice(related)

	_, err = attachStickerStickerKeywords0(ctx, exec, len(related), stickerKeywords1, sticker0)
	if err != nil {
		return err
	}

	sticker0.R.StickerKeywords = append(sticker0.R.StickerKeywords, stickerKeywords1...)

	for _, rel := range related {
		rel.R.Sticker = sticker0
	}

	return nil
}

type stickerWhere[Q sqlite.Filterable] struct {
	ID          sqlite.WhereMod[Q, int64]
	FileID      sqlite.WhereMod[Q, string]
	StickerType sqlite.WhereMod[Q, string]
	CreatedAt   sqlite.WhereMod[Q, time.Time]
	UpdatedAt   sqlite.WhereMod[Q, time.Time]
}

func (stickerWhere[Q]) AliasedAs(alias string) stickerWhere[Q] {
	return buildStickerWhere[Q](buildStickerColumns(alias))
}

func buildStickerWhere[Q sqlite.Filterable](cols stickerColumns) stickerWhere[Q] {
	return stickerWhere[Q]{
		ID:          sqlite.Where[Q, int64](cols.ID),
		FileID:      sqlite.Where[Q, string](cols.FileID),
		StickerType: sqlite.Where[Q, string](cols.StickerType),
		CreatedAt:   sqlite.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:   sqlite.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *Sticker) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "StickerKeywords":
		rels, ok := retrieved.(StickerKeywordSlice)
		if !ok {
			return fmt.Errorf("sticker cannot load %T as %q", retrieved, name)
		}

		o.R.StickerKeywords = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Sticker = o
			}
		}
		return nil
	default:
		return fmt.Errorf("sticker has no relationship %q", name)
	}
}

type stickerPreloader struct{}

func buildStickerPreloader() stickerPreloader {
	return stickerPreloader{}
}

type stickerThenLoader[Q orm.Loadable] struct {
	StickerKeywords func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildStickerThenLoader[Q orm.Loadable]() stickerThenLoader[Q] {
	type StickerKeywordsLoadInterface interface {
		LoadStickerKeywords(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return stickerThenLoader[Q]{
		StickerKeywords: thenLoadBuilder[Q](
			"StickerKeywords",
			func(ctx context.Context, exec bob.Executor, retrieved StickerKeywordsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadStickerKeywords(ctx, exec, mods...)
			},
		),
	}
}

// LoadStickerKeywords loads the sticker's StickerKeywords into the .R struct
func (o *Sticker) LoadStickerKeywords(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.StickerKeywords = nil

	related, err := o.StickerKeywords(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Sticker = o
	}

	o.R.StickerKeywords = related
	return nil
}

// LoadStickerKeywords loads the sticker's StickerKeywords into the .R struct
func (os StickerSlice) LoadStickerKeywords(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	stickerKeywords, err := os.StickerKeywords(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.StickerKeywords = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range stickerKeywords {

			if !(o.ID == rel.StickerID) {
				continue
			}

			rel.R.Sticker = o

			o.R.StickerKeywords = append(o.R.StickerKeywords, rel)
		}
	}

	return nil
}

type stickerJoins[Q dialect.Joinable] struct {
	typ             string
	StickerKeywords modAs[Q, stickerKeywordColumns]
}

func (j stickerJoins[Q]) aliasedAs(alias string) stickerJoins[Q] {
	return buildStickerJoins[Q](buildStickerColumns(alias), j.typ)
}

func buildStickerJoins[Q dialect.Joinable](cols stickerColumns, typ string) stickerJoins[Q] {
	return stickerJoins[Q]{
		typ: typ,
		StickerKeywords: modAs[Q, stickerKeywordColumns]{
			c: StickerKeywords.Columns,
			f: func(to stickerKeywordColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, StickerKeywords.Name().As(to.Alias())).On(
						to.StickerID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
